import {icon} from './icons.js';
import {escapeHTML as e,number} from '../core/utils.js';
export const button=(label,action,ic='',variant='',attrs='')=>`<button class="btn ${variant}" data-action="${action}" ${attrs}>${ic?icon(ic,14):''}<span>${e(label)}</span></button>`;
export const ib=(label,action,ic,active=false,attrs='')=>`<button class="icon-button ${active?'active':''}" data-action="${action}" title="${e(label)}" aria-label="${e(label)}" ${attrs}>${icon(ic,15)}</button>`;
export const badge=(label,type='')=>`<span class="badge ${type}">${['verified','approved','success','matched','green'].includes(type)?icon('check',10):''}${e(label)}</span>`;
export const notice=(text,type='')=>`<div class="notice ${type}">${icon(type==='warning'?'warning':'info',15)}<div>${text}</div></div>`;
export const heading=(title,description,ic,actions='',teal=false)=>`<header class="page-heading"><div class="heading-name"><div class="heading-icon ${teal?'teal':''}">${icon(ic,24)}</div><div><h1>${e(title)}</h1><p class="subheading">${e(description)}</p></div></div><div class="actions">${actions}</div></header>`;
export const tabs=(items,current,scope)=>`<div class="tabs" role="tablist">${items.map(([id,label,count])=>`<button role="tab" aria-selected="${current===id}" class="tab ${current===id?'active':''}" data-action="tab" data-scope="${scope}" data-value="${id}">${e(label)}${count!=null?`<span class="count">${e(count)}</span>`:''}</button>`).join('')}</div>`;
export const field=(label,name,value='',type='text',extra='')=>`<label class="form-field"><span>${e(label)}</span><input name="${name}" type="${type}" value="${e(value)}" ${extra}></label>`;
export const selectField=(label,name,options,value,extra='')=>`<label class="form-field"><span>${e(label)}</span><select name="${name}" ${extra}>${options.map(o=>{const[k,l]=Array.isArray(o)?o:[o,o];return `<option value="${e(k)}" ${String(k)===String(value)?'selected':''}>${e(l)}</option>`;}).join('')}</select></label>`;
export function table(rows,columns,{rowAction='',idKey='id',selected=null,empty='No records to display.',cellAction=''}={}){if(!rows.length)return `<div class="empty">${icon('table',28)}<p>${e(empty)}</p></div>`;return `<div class="table-wrap"><table class="data-table"><thead><tr>${columns.map(c=>`<th>${e(typeof c==='string'?c:c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr class="${rowAction?'clickable':''} ${selected===r[idKey]?'selected':''}" ${rowAction?`data-action="${rowAction}" data-id="${e(r[idKey]??i)}"`:''}>${columns.map(c=>{const key=typeof c==='string'?c:c.key,val=r[key];return `<td ${cellAction?`data-action="${cellAction}" data-row="${i}" data-key="${e(key)}" tabindex="0" title="Click to edit"`:''}>${typeof c==='object'&&c.render?c.render(val,r):e(typeof val==='object'&&val!=null?JSON.stringify(val):val??'—')}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
export function metric(title,value,description,ic='chart'){return `<div class="metric-card"><div class="metric-top"><span>${e(title)}</span>${icon(ic,16)}</div><div class="metric-value">${e(value)}</div><div class="metric-note">${description}</div></div>`;}
export function chart(values,{height=170,width=680,label='Pressure (bar)',color='var(--accent)',mini=false}={}){const v=values.filter(Number.isFinite);if(!v.length)return `<div class="empty tiny">No numeric observations.</div>`;const min=Math.min(...v),max=Math.max(...v),range=max-min||1,pad=mini?2:30,top=mini?3:18,bottom=mini?3:24;const points=v.map((y,i)=>[pad+i/Math.max(1,v.length-1)*(width-pad-13),top+(max-y)/range*(height-top-bottom)]);const line=points.map(p=>p.join(',')).join(' ');return `<svg class="${mini?'sparkline':'line-chart'}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${e(label)}">${mini?'':Array.from({length:4},(_,i)=>{const y=top+i/3*(height-top-bottom);return `<line x1="${pad}" x2="${width-10}" y1="${y}" y2="${y}" stroke="var(--border)" stroke-dasharray="3 4"/><text x="${pad-7}" y="${y+3}" fill="var(--muted)" font-size="9" text-anchor="end">${(max-i/3*range).toFixed(1)}</text>`;}).join('')}<polygon points="${pad},${height-bottom} ${line} ${width-13},${height-bottom}" fill="${color}" opacity=".055"/><polyline points="${line}" fill="none" stroke="${color}" stroke-width="${mini?1.5:2}" stroke-linejoin="round"/>${mini?'':`<text x="${pad}" y="${height-4}" fill="var(--muted)" font-size="9">Earlier</text><text x="${width-12}" y="${height-4}" text-anchor="end" fill="var(--muted)" font-size="9">Latest sample</text>`}</svg>`;}
export const empty=(title,description,action='')=>`<div class="empty">${icon('layers',32)}<h3>${e(title)}</h3><p>${e(description)}</p>${action}</div>`;
