import {Renderer} from './renderer.js';
import {buildDiagramScene,connectionPoints} from './primitives.js';
import {uid,clamp} from '../core/utils.js';
import {SYMBOLS} from '../core/seed.js';
export class DiagramEditor {
 constructor(host,store,{onSelect=()=>{},onChange=()=>{},onStats=()=>{},onError=()=>{}}={}){this.host=host;this.store=store;this.onSelect=onSelect;this.onChange=onChange;this.onError=onError;this.renderer=new Renderer(host,{onStats});this.selection='p101a';this.selectedEdge=null;this.tool='select';this.showLabels=true;this.showSignals=true;this.snap=true;this.highlight=new Set();this.pointers=new Map();this.abort=new AbortController();const signal=this.abort.signal,c=this.renderer.overlay;c.addEventListener('pointerdown',e=>this.down(e),{signal});c.addEventListener('pointermove',e=>this.move(e),{signal});c.addEventListener('pointerup',e=>this.up(e),{signal});c.addEventListener('pointercancel',e=>this.cancel(e),{signal});c.addEventListener('wheel',e=>this.wheel(e),{passive:false,signal});c.addEventListener('contextmenu',e=>e.preventDefault(),{signal});c.addEventListener('keydown',e=>this.key(e),{signal});this.refresh();requestAnimationFrame(()=>{this.renderer.resize();this.fit();});}
 get diagram(){return this.store.diagram;}
 setTool(tool){this.tool=tool;this.connectStart=null;this.host.dataset.tool=tool;this.onChange({tool});}
 point(e){const r=this.host.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 hit(p){let nearest=null,distance=Infinity;for(const n of this.diagram.nodes){const w=n.boxWidth||(['tank'].includes(n.type)?100:70),h=n.boxHeight||(n.type==='tank'?185:90);const dx=Math.abs(p.x-n.x),dy=Math.abs(p.y-n.y);if(dx<w/2&&dy<h/2){const dist=dx*dx+dy*dy;if(dist<distance){nearest=n;distance=dist;}}}return nearest;}
 hitEdge(p){for(const edge of [...this.diagram.edges].reverse()){if(edge.kind==='signal'&&!this.showSignals)continue;const points=connectionPoints(edge,this.diagram);for(let i=0;i<points.length-1;i++){const [x,y]=points[i],[x2,y2]=points[i+1],dx=x2-x,dy=y2-y,l=dx*dx+dy*dy;const t=l?clamp(((p.x-x)*dx+(p.y-y)*dy)/l,0,1):0;if(Math.hypot(p.x-x-dx*t,p.y-y-dy*t)<7/this.renderer.view.scale)return edge;}}return null;}
 select(id,edge=false){this.selection=edge?null:id;this.selectedEdge=edge?id:null;this.onSelect(edge?{edge:id}:id);this.refresh();}
 down(e){try{e.preventDefault();this.renderer.overlay.focus();const p=this.point(e);this.pointers.set(e.pointerId,p);this.renderer.overlay.setPointerCapture(e.pointerId);if(this.pointers.size===2){const [a,b]=[...this.pointers.values()];const center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};this.pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),scale:this.renderer.view.scale,world:this.renderer.toWorld(center.x,center.y)};this.drag=null;return;}const w=this.renderer.toWorld(p.x,p.y),hit=this.hit(w);if(e.button===1||e.button===2||e.altKey||this.tool==='pan'){this.drag={kind:'pan',p,view:{...this.renderer.view}};return;}
 if(this.tool.startsWith('add:')){this.store.checkEdit();const type=this.tool.split(':')[1],def=SYMBOLS[type],id=uid('node');let num=101;while(this.diagram.nodes.some(n=>n.tag===`${def.prefix}-${num}`))num++;this.store.transact('Add diagram component',()=>this.diagram.nodes.push({id,type,tag:`${def.prefix}-${num}`,name:def.label,x:this.snap?Math.round(w.x/10)*10:w.x,y:this.snap?Math.round(w.y/10)*10:w.y,rotation:0,status:'review',source:'Manual annotation',diameter:100,lineClass:'CS150',unit:'Unit 100',designPressure:16,operatingPressure:0,temperature:20}));this.select(id);this.setTool('select');return;}
 if(this.tool==='pipe'||this.tool==='signal'){this.store.checkEdit();if(!hit)return;if(!this.connectStart){this.connectStart=hit.id;this.select(hit.id);}else if(hit.id!==this.connectStart){const from=this.connectStart,id=uid('edge');this.store.transact('Connect components',()=>this.diagram.edges.push({id,from,to:hit.id,kind:this.tool==='signal'?'signal':'process',tag:`${this.tool==='signal'?'SIG':'LINE'}-${this.diagram.edges.length+1}`,points:[],diameter:100,lineClass:'CS150'}));this.connectStart=null;this.select(id,true);}return;}
 if(hit){this.select(hit.id);if(this.store.state.settings.role!=='viewer')this.drag={kind:'node',id:hit.id,p:w,start:{x:hit.x,y:hit.y},preview:{id:hit.id,x:hit.x,y:hit.y}};}else{const edge=this.hitEdge(w);if(edge){this.select(edge.id,true);return;}this.select(null);this.drag={kind:'pan',p,view:{...this.renderer.view}};}
 }catch(err){this.onError(err);}}
 move(e){const p=this.point(e);if(this.pointers.has(e.pointerId))this.pointers.set(e.pointerId,p);if(this.pinch&&this.pointers.size===2){const[a,b]=[...this.pointers.values()],center={x:(a.x+b.x)/2,y:(a.y+b.y)/2};const scale=clamp(this.pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,this.pinch.distance),.06,5);this.renderer.setView({scale,x:center.x-this.pinch.world.x*scale,y:center.y-this.pinch.world.y*scale});return;}if(!this.drag){const w=this.renderer.toWorld(p.x,p.y);this.host.style.cursor=this.tool==='pan'?'grab':this.tool!=='select'?'crosshair':this.hit(w)?'move':'default';return;}
 if(this.drag.kind==='pan')this.renderer.setView({x:this.drag.view.x+p.x-this.drag.p.x,y:this.drag.view.y+p.y-this.drag.p.y});else{const w=this.renderer.toWorld(p.x,p.y),x=this.drag.start.x+w.x-this.drag.p.x,y=this.drag.start.y+w.y-this.drag.p.y;this.drag.preview={id:this.drag.id,x:this.snap?Math.round(x/10)*10:x,y:this.snap?Math.round(y/10)*10:y};this.refresh(this.drag.preview);}}
 up(e){this.pointers.delete(e.pointerId);if(this.pinch){this.pinch=null;this.drag=null;return;}if(this.drag?.kind==='node'){const {id,preview,start}=this.drag;this.drag=null;if(preview.x!==start.x||preview.y!==start.y){try{this.store.transact('Move component',()=>Object.assign(this.diagram.nodes.find(n=>n.id===id),{x:preview.x,y:preview.y}));this.onChange({moved:id});}catch(err){this.onError(err);}}this.refresh();}this.drag=null;}
 cancel(e){this.pointers.delete(e.pointerId);this.drag=null;this.pinch=null;this.refresh();}
 wheel(e){e.preventDefault();const p=this.point(e),w=this.renderer.toWorld(p.x,p.y),scale=clamp(this.renderer.view.scale*Math.exp(-e.deltaY*.0015),.06,6);this.renderer.setView({scale,x:p.x-w.x*scale,y:p.y-w.y*scale});this.onChange({zoom:scale});}
 zoom(factor){const v=this.renderer.view,c={x:this.renderer.width/2,y:this.renderer.height/2},w=this.renderer.toWorld(c.x,c.y),scale=clamp(v.scale*factor,.06,6);this.renderer.setView({scale,x:c.x-w.x*scale,y:c.y-w.y*scale});this.onChange({zoom:scale});}
 fit(){this.renderer.fit(this.diagram.width,this.diagram.height,16);this.onChange({zoom:this.renderer.view.scale});}
 focus(id){const node=this.diagram.nodes.find(n=>n.id===id);if(!node)return;this.select(id);const scale=Math.max(this.renderer.view.scale,.9);this.renderer.setView({scale,x:this.renderer.width/2-node.x*scale,y:this.renderer.height/2-node.y*scale});}
 remove(){if(!this.selection&&!this.selectedEdge)return;this.store.transact('Delete diagram selection',()=>{if(this.selection){this.diagram.nodes=this.diagram.nodes.filter(n=>n.id!==this.selection);this.diagram.edges=this.diagram.edges.filter(e=>e.from!==this.selection&&e.to!==this.selection);}else this.diagram.edges=this.diagram.edges.filter(e=>e.id!==this.selectedEdge);});this.select(null);}
 duplicate(){const n=this.diagram.nodes.find(n=>n.id===this.selection);if(!n)return;const id=uid('node');let tag=n.tag+'-COPY',i=2;while(this.diagram.nodes.some(n=>n.tag===tag))tag=n.tag+`-COPY${i++}`;this.store.transact('Duplicate component',()=>this.diagram.nodes.push({...structuredClone(n),id,tag,x:n.x+60,y:n.y+60,status:'review'}));this.select(id);}
 rotate(){const n=this.diagram.nodes.find(n=>n.id===this.selection);if(!n)return;this.store.transact('Rotate component',()=>n.rotation=((n.rotation||0)+90)%360);this.refresh();}
 key(e){try{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.remove();}if(e.key==='Escape'){this.setTool('select');this.highlight.clear();this.refresh();}if(e.key.toLowerCase()==='f')this.fit();if(e.key.toLowerCase()==='r')this.rotate();if(e.key.toLowerCase()==='v')this.setTool('select');if(e.key.toLowerCase()==='h')this.setTool('pan');if(e.key.toLowerCase()==='p')this.setTool('pipe');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();this.duplicate();}}catch(err){this.onError(err);}}
 refresh(preview=null){this.renderer.setBackground(this.diagram.background?.data||null);this.renderer.setScene(buildDiagramScene(this.diagram,{selected:this.selection,selectedEdge:this.selectedEdge,highlight:this.highlight,showLabels:this.showLabels,showSignals:this.showSignals,preview}));}
 destroy(){this.abort.abort();this.renderer.destroy();}
}
