/** Shared WebGPU device and parallel numeric analysis. No rendering library. */
export class GPUService extends EventTarget {
 constructor(){super();this.device=null;this.adapter=null;this.reason='Initializing';this.mode='Initializing';this._ready=null;}
 async init(){if(this._ready)return this._ready;this._ready=(async()=>{try{if(!navigator.gpu)throw Error('WebGPU is not available in this browser/context');this.adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!this.adapter)throw Error('No WebGPU adapter');this.device=await this.adapter.requestDevice();this.device.addEventListener('uncapturederror',e=>console.error('WebGPU:',e.error.message));this.device.lost.then(info=>{this.device=null;this.mode='Canvas 2D';this.reason='GPU device lost: '+info.message;this.dispatchEvent(new Event('change'));});this.mode='WebGPU';this.reason=this.adapter.info?.description||this.adapter.info?.device||'GPU accelerated';}catch(e){this.mode='Canvas 2D';this.reason=e.message;}this.dispatchEvent(new Event('change'));return this;})();return this._ready;}
 async anomalies(values,threshold=2.5){if(!Array.isArray(values)||!values.every(Number.isFinite))throw Error('Anomaly input must contain only finite numbers');if(!Number.isFinite(threshold)||threshold<0)throw Error('Threshold must be finite and non-negative');const start=performance.now(),n=values.length;const mean=n?values.reduce((a,b)=>a+b,0)/n:0,std=n?Math.sqrt(values.reduce((s,v)=>s+(v-mean)**2,0)/n):0;if(!n)return {scores:[],flags:[],mean,std,duration:0,mode:'CPU'};await this.init();if(!this.device||n*4>this.device.limits.maxStorageBufferBindingSize||Math.ceil(n/256)>this.device.limits.maxComputeWorkgroupsPerDimension)return cpu();const device=this.device;let buffers=[];try{
 const module=device.createShaderModule({label:'Stratum numeric anomaly compute',code:`struct Params { mean:f32, deviation:f32, threshold:f32, count:u32 };
 @group(0) @binding(0) var<storage,read> values:array<f32>;
 @group(0) @binding(1) var<storage,read_write> scores:array<f32>;
 @group(0) @binding(2) var<uniform> params:Params;
 @compute @workgroup_size(256) fn main(@builtin(global_invocation_id) id:vec3u){ if(id.x>=params.count){return;} scores[id.x]=select(0.0,abs(values[id.x]-params.mean)/max(params.deviation,0.0000001),params.deviation>0.0); }`});
 const pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module,entryPoint:'main'}});
 const input=device.createBuffer({size:n*4,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});const output=device.createBuffer({size:n*4,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});const read=device.createBuffer({size:n*4,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const uniform=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});buffers=[input,output,read,uniform];const params=new ArrayBuffer(16);new Float32Array(params).set([mean,std,threshold]);new Uint32Array(params)[3]=n;
 device.queue.writeBuffer(input,0,new Float32Array(values));device.queue.writeBuffer(uniform,0,params);
 const group=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:input}},{binding:1,resource:{buffer:output}},{binding:2,resource:{buffer:uniform}}]});const enc=device.createCommandEncoder();const pass=enc.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,group);pass.dispatchWorkgroups(Math.ceil(n/256));pass.end();enc.copyBufferToBuffer(output,0,read,0,n*4);device.queue.submit([enc.finish()]);await read.mapAsync(GPUMapMode.READ);const scores=Array.from(new Float32Array(read.getMappedRange()));read.unmap();return {scores,flags:scores.map(s=>s>threshold),mean,std,duration:performance.now()-start,mode:'WebGPU compute'};
 }catch(e){console.warn('Compute fallback',e);return cpu();}finally{buffers.forEach(b=>b.destroy());}
 function cpu(){const scores=values.map(v=>std?Math.abs(v-mean)/std:0);return {scores,flags:scores.map(s=>s>threshold),mean,std,duration:performance.now()-start,mode:'CPU'};}
 }
}
export const gpu=new GPUService();
