import {gpu} from './gpu.js';
import {tessellate,drawCanvasScene,Scene} from './primitives.js';
/** Retained geometry: view changes update only 32 uniform bytes, not vertices. */
export class Renderer {
 constructor(host,{grid=true,onStats=()=>{}}={}){this.host=host;this.grid=grid;this.onStats=onStats;this.view={x:0,y:0,scale:1};this.scene=new Scene();this.mode='Canvas 2D';this.destroyed=false;this.canvas=document.createElement('canvas');this.canvas.className='scene-canvas';this.overlay=document.createElement('canvas');this.overlay.className='scene-overlay';this.overlay.setAttribute('aria-label','Interactive engineering canvas');this.overlay.tabIndex=0;host.append(this.canvas,this.overlay);this.ctx=this.overlay.getContext('2d');this.width=1;this.height=1;this.dpr=Math.min(devicePixelRatio||1,2);this.dirtyGeometry=true;this.background=null;this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.deviceChange=()=>{if(!gpu.device&&this.mode==='WebGPU'){this.mode='Canvas 2D';this.device=null;this.requestDraw();}};gpu.addEventListener('change',this.deviceChange);this.ready=this.initialize();}
 async initialize(){await gpu.init();if(this.destroyed)return;try{if(!gpu.device)throw Error(gpu.reason);this.device=gpu.device;this.context=this.canvas.getContext('webgpu');if(!this.context)throw Error('No WebGPU canvas');this.format=navigator.gpu.getPreferredCanvasFormat();this.context.configure({device:this.device,format:this.format,alphaMode:'premultiplied'});const module=this.device.createShaderModule({label:'Stratum vector shader',code:`struct View { offset:vec2f, viewport:vec2f, scale:f32, pad1:f32, pad2:f32, pad3:f32 };
 @group(0) @binding(0) var<uniform> view:View;
 struct Output { @builtin(position) position:vec4f, @location(0) color:vec4f };
 @vertex fn vertex(@location(0) position:vec2f,@location(1) color:vec4f)->Output { var out:Output; let p=(position*view.scale+view.offset)/view.viewport*2.0-1.0;out.position=vec4f(p.x,-p.y,0.0,1.0);out.color=color;return out; }
 @fragment fn fragment(input:Output)->@location(0) vec4f { return input.color; }`});
 this.pipeline=await this.device.createRenderPipelineAsync({label:'Stratum batched vectors',layout:'auto',vertex:{module,entryPoint:'vertex',buffers:[{arrayStride:24,attributes:[{shaderLocation:0,offset:0,format:'float32x2'},{shaderLocation:1,offset:8,format:'float32x4'}]}]},fragment:{module,entryPoint:'fragment',targets:[{format:this.format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list'}});
 if(this.destroyed)return;this.uniform=this.device.createBuffer({size:32,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.bindGroup=this.device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniform}}]});this.mode='WebGPU';this.dirtyGeometry=true;this.requestDraw();}catch(e){this.mode='Canvas 2D';this.device=null;this.reason=e.message;this.requestDraw();}}
 resize(){if(this.destroyed)return;const r=this.host.getBoundingClientRect();this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);for(const c of [this.canvas,this.overlay]){c.width=Math.ceil(this.width*this.dpr);c.height=Math.ceil(this.height*this.dpr);}this.requestDraw();}
 setScene(scene){this.scene=scene;this.dirtyGeometry=true;this.requestDraw();}
 setBackground(src){if(this.backgroundSrc===src)return;this.backgroundSrc=src;this.background=null;if(src){const image=new Image();image.onload=()=>{if(this.backgroundSrc===src){this.background=image;this.requestDraw();}};image.src=src;}this.requestDraw();}
 setView(view){Object.assign(this.view,view);this.requestDraw();}
 fit(width,height,padding=20){const scale=Math.min((this.width-padding*2)/width,(this.height-padding*2)/height);this.setView({scale:Math.max(.04,scale),x:(this.width-width*scale)/2,y:(this.height-height*scale)/2});}
 toWorld(x,y){return {x:(x-this.view.x)/this.view.scale,y:(y-this.view.y)/this.view.scale};}
 requestDraw(){if(this.frame||this.destroyed)return;this.frame=requestAnimationFrame(()=>{this.frame=null;this.draw();});}
 draw(){if(this.destroyed)return;const t=performance.now();const ctx=this.ctx;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,this.width,this.height);this.host.style.setProperty('--grid-size',`${Math.max(8,20*this.view.scale)}px`);this.host.style.setProperty('--grid-x',`${this.view.x}px`);this.host.style.setProperty('--grid-y',`${this.view.y}px`);this.host.classList.toggle('no-grid',!this.grid);
 // Imported source image stays below vectors, including on WebGPU.
 if(this.background){this.host.style.backgroundImage='none';this.host.style.backgroundColor='#fff';}else{this.host.style.backgroundImage='';this.host.style.backgroundColor='';}
 if(this.mode==='WebGPU'&&this.device){try{if(this.dirtyGeometry){const data=tessellate(this.scene);this.vertexCount=data.length/6;if(!this.vertices||this.capacity<data.byteLength){this.vertices?.destroy();this.capacity=Math.max(1024,data.byteLength*2);this.vertices=this.device.createBuffer({size:this.capacity,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});}if(data.length)this.device.queue.writeBuffer(this.vertices,0,data);this.dirtyGeometry=false;}
 this.device.queue.writeBuffer(this.uniform,0,new Float32Array([this.view.x,this.view.y,this.width,this.height,this.view.scale,0,0,0]));const command=this.device.createCommandEncoder();const pass=command.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'store'}]});if(this.vertexCount){pass.setPipeline(this.pipeline);pass.setBindGroup(0,this.bindGroup);pass.setVertexBuffer(0,this.vertices);pass.draw(this.vertexCount);}pass.end();this.device.queue.submit([command.finish()]);}catch(e){console.warn('Renderer fallback',e);this.mode='Canvas 2D';this.device=null;}}
 if(this.background){if(!this.imageCanvas){this.imageCanvas=document.createElement('canvas');this.imageCanvas.className='background-canvas';this.host.prepend(this.imageCanvas);}this.imageCanvas.width=this.overlay.width;this.imageCanvas.height=this.overlay.height;const b=this.imageCanvas.getContext('2d');b.setTransform(this.dpr,0,0,this.dpr,0,0);b.translate(this.view.x,this.view.y);b.scale(this.view.scale,this.view.scale);b.drawImage(this.background,0,0);}else this.imageCanvas?.remove();if(!this.background)this.imageCanvas=null;
 this.canvas.style.visibility=this.mode==='WebGPU'?'visible':'hidden';
 if(this.mode!=='WebGPU')drawCanvasScene(ctx,this.scene,this.view);
 ctx.save();ctx.translate(this.view.x,this.view.y);ctx.scale(this.view.scale,this.view.scale);for(const l of this.scene.labels){if(this.view.scale<.25&&!l.always)continue;const x=l.x*this.view.scale+this.view.x,y=l.y*this.view.scale+this.view.y;if(x<-150||y<-30||x>this.width+150||y>this.height+30)continue;ctx.font=`${l.weight||400} ${l.size||12}px ${l.mono?'ui-monospace, monospace':'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'}`;ctx.textAlign=l.align||'center';ctx.textBaseline='alphabetic';ctx.fillStyle=l.color||'#526275';ctx.fillText(l.text,l.x,l.y);}ctx.restore();this.lastDuration=performance.now()-t;this.onStats({mode:this.mode,duration:this.lastDuration,vertices:this.vertexCount||0,primitives:this.scene.shapes.length});}
 async png(width,height){const c=document.createElement('canvas');const scale=Math.min(2,4096/Math.max(width,height));c.width=width*scale;c.height=height*scale;const ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);if(this.background)ctx.drawImage(this.background,0,0);drawCanvasScene(ctx,this.scene,{x:0,y:0,scale:1});for(const l of this.scene.labels){ctx.font=`${l.weight||400} ${l.size||12}px sans-serif`;ctx.textAlign=l.align||'center';ctx.fillStyle=l.color||'#526275';ctx.fillText(l.text,l.x,l.y);}return await new Promise(resolve=>c.toBlob(resolve,'image/png'));}
 destroy(){this.destroyed=true;this.observer.disconnect();gpu.removeEventListener('change',this.deviceChange);cancelAnimationFrame(this.frame);this.vertices?.destroy();this.uniform?.destroy();this.context?.unconfigure();this.canvas.remove();this.overlay.remove();this.imageCanvas?.remove();}
}
