import {assert,groupBy} from './utils.js';
export function parseCSV(text){
 text=String(text).replace(/^\uFEFF/,'');const records=[];let row=[],field='',quoted=false;
 for(let i=0;i<=text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){field+='"';i++;}else quoted=false;}else if(c===undefined)throw Error('Unterminated CSV quote');else field+=c;}else if(c==='"'&&field==='')quoted=true;else if(c===','||c==='\n'||c==='\r'||c===undefined){row.push(field);field='';if(c!==','){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(v=>v!==''))records.push(row);row=[];}}else field+=c;}
 if(!records.length)return [];const headers=records.shift().map((s,i)=>s.trim()||`column_${i+1}`);assert(new Set(headers).size===headers.length,'CSV headers must be unique');assert(!headers.some(h=>['__proto__','prototype','constructor'].includes(h)),'Reserved column name');
 return records.map((r,i)=>{assert(r.length<=headers.length,`Row ${i+2} has too many fields`);return Object.fromEntries(headers.map((h,j)=>[h,inferValue(r[j]??'')]));});
}
export function inferValue(v){if(v==='')return null;if(v==='true')return true;if(v==='false')return false;if(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:e[+-]?\d+)?$/i.test(v)&&Number.isFinite(+v)&&(!/^0\d/.test(v))&&Math.abs(+v)<=Number.MAX_SAFE_INTEGER)return +v;return v;}
export function toCSV(rows,{spreadsheetSafe=true}={}){if(!rows.length)return '';const headers=[...new Set(rows.flatMap(Object.keys))];const enc=v=>{let s=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);if(spreadsheetSafe&&typeof v==='string'&&/^[\s]*[=+@-]/.test(s))s="'"+s;return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;};return [headers.map(enc).join(','),...rows.map(r=>headers.map(h=>enc(r[h])).join(','))].join('\r\n');}
export function profile(rows){const columns=[...new Set(rows.flatMap(Object.keys))];return columns.map(name=>{const values=rows.map(r=>r[name]),present=values.filter(v=>v!=null&&v!==''),nums=present.filter(v=>typeof v==='number'&&Number.isFinite(v));return {name,type:!present.length?'empty':nums.length===present.length?'number':present.every(v=>typeof v==='boolean')?'boolean':'string',count:values.length,nulls:values.length-present.length,distinct:new Set(present.map(String)).size,completeness:values.length?present.length/values.length:1,min:nums.length?nums.reduce((a,b)=>Math.min(a,b),Infinity):null,max:nums.length?nums.reduce((a,b)=>Math.max(a,b),-Infinity):null,mean:nums.length?nums.reduce((s,n)=>s+n,0)/nums.length:null};});}
export function tokenize(text){const out=[];let i=0;while(i<text.length){const rest=text.slice(i);const space=/^\s+/.exec(rest);if(space){i+=space[0].length;continue;}const s=/^'(?:''|[^'])*'|^"(?:""|[^"])*"/.exec(rest);if(s){out.push({type:'literal',value:s[0].slice(1,-1).replace(s[0][0]==="'"?/''/g:/""/g,s[0][0]),start:i,end:i+s[0].length});i+=s[0].length;continue;}const n=/^(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?/i.exec(rest);if(n){out.push({type:'literal',value:+n[0],start:i,end:i+n[0].length});i+=n[0].length;continue;}const op=/^(?:>=|<=|!=|<>|==|&&|\|\||[+\-*\/%=><!(),])/.exec(rest);if(op){out.push({type:'op',value:op[0],start:i,end:i+op[0].length});i+=op[0].length;continue;}const id=/^[a-zA-Z_$][\w.$]*/.exec(rest);if(id){const k=id[0].toLowerCase();out.push({type:['true','false','null'].includes(k)?'literal':'id',value:k==='true'?true:k==='false'?false:k==='null'?null:id[0],start:i,end:i+id[0].length});i+=id[0].length;continue;}throw Error(`Unexpected expression character at ${i+1}: ${text[i]}`);}return out;}
const funcs={abs:Math.abs,round:(x,n=0)=>Math.round(x*10**n)/10**n,lower:x=>String(x??'').toLowerCase(),upper:x=>String(x??'').toUpperCase(),length:x=>String(x??'').length,coalesce:(...xs)=>xs.find(x=>x!=null),contains:(x,y)=>String(x??'').toLowerCase().includes(String(y??'').toLowerCase()),sqrt:Math.sqrt,min:Math.min,max:Math.max};
export function compileExpression(text){
 const tokens=tokenize(String(text));let i=0,depth=0;const peek=()=>String(tokens[i]?.value??'').toLowerCase();const take=()=>tokens[i++];
 function primary(){assert(++depth<100,'Expression nesting limit');let node;const t=take();assert(t,'Incomplete expression');const k=String(t.value).toLowerCase();if(['-','+','!','not'].includes(k)){node={kind:'unary',op:k,arg:k==='not'?expr(3):primary()};}else if(t.value==='('){node=expr(0);assert(take()?.value===')','Missing closing parenthesis');}else if(t.type==='literal')node={kind:'literal',value:t.value};else if(t.type==='id'){assert(!['__proto__','constructor','prototype'].includes(k),'Reserved identifier');if(peek()==='('){assert(funcs[k],'Unknown function: '+k);take();const args=[];if(peek()!==')'){do{args.push(expr(0));if(peek()!==',')break;take();}while(true);}assert(take()?.value===')','Missing closing function parenthesis');node={kind:'call',name:k,args};}else node={kind:'field',name:t.value};}else throw Error('Unexpected token: '+t.value);depth--;return node;}
 const prec={or:1,'||':1,and:2,'&&':2,'=':3,'==':3,'!=':3,'<>':3,'>':3,'<':3,'>=':3,'<=':3,like:3,is:3,'+':4,'-':4,'*':5,'/':5,'%':5};
 function expr(min){let left=primary();while(prec[peek()]>=min){const op=peek(),p=prec[op];take();let actual=op;if(op==='is'&&peek()==='not'){take();actual='is not';}left={kind:'binary',op:actual,left,right:expr(p+1)};}return left;}
 const ast=expr(0);assert(i===tokens.length,'Unexpected trailing expression');
 function evalNode(n,r){if(n.kind==='literal')return n.value;if(n.kind==='field')return Object.hasOwn(r,n.name)?r[n.name]:null;if(n.kind==='call')return funcs[n.name](...n.args.map(a=>evalNode(a,r)));if(n.kind==='unary'){const v=evalNode(n.arg,r);return n.op==='-'?-Number(v):n.op==='+'?Number(v):!v;}const a=evalNode(n.left,r);if(n.op==='and'||n.op==='&&')return !!a&&!!evalNode(n.right,r);if(n.op==='or'||n.op==='||')return !!a||!!evalNode(n.right,r);const b=evalNode(n.right,r);switch(n.op){case '=':case '==':case 'is':return a===b;case '!=':case '<>':case 'is not':return a!==b;case '>':return a>b;case '<':return a<b;case '>=':return a>=b;case '<=':return a<=b;case '+':return Number(a)+Number(b);case '-':return Number(a)-Number(b);case '*':return Number(a)*Number(b);case '/':return Number(b)===0?null:Number(a)/Number(b);case '%':return Number(b)===0?null:Number(a)%Number(b);case 'like':{const pattern=String(b).replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replace(/%/g,'.*').replace(/_/g,'.');return new RegExp('^'+pattern+'$','i').test(String(a??''));}default:throw Error('Unknown operator');}}
 return row=>evalNode(ast,row);
}
export function aggregate(rows,group,measures=[{column:'*',op:'count',as:'count'}]){const groups=group?groupBy(rows,group):new Map([['all',rows]]);return [...groups].map(([key,rs])=>{const out=group?{[group]:key}:{};for(const m of measures){assert(['count','sum','avg','min','max'].includes(m.op),'Unsupported aggregate operation');const present=rs.map(r=>r[m.column]).filter(v=>v!=null&&v!=='');const v=present.map(Number).filter(Number.isFinite);out[m.as||`${m.op}_${m.column}`]=m.op==='count'?(m.column==='*'?rs.length:present.length):m.op==='sum'?v.reduce((a,b)=>a+b,0):m.op==='avg'?(v.length?v.reduce((a,b)=>a+b,0)/v.length:null):m.op==='min'?(v.length?v.reduce((a,b)=>Math.min(a,b),Infinity):null):m.op==='max'?(v.length?v.reduce((a,b)=>Math.max(a,b),-Infinity):null):null;}return out;});}
function splitExpressions(text){
 const tokens=tokenize(text),parts=[];let depth=0,start=0;
 for(const t of tokens){if(t.type==='op'&&t.value==='(')depth++;if(t.type==='op'&&t.value===')')depth--;if(t.type==='op'&&t.value===','&&depth===0){parts.push(text.slice(start,t.start).trim());start=t.end;}}
 parts.push(text.slice(start).trim());assert(parts.every(Boolean),'Empty SELECT expression');return parts;
}
export function executeQuery(query,tables){
 const m=/^\s*select\s+(.+?)\s+from\s+([\w-]+)([\s\S]*?)\s*;?\s*$/i.exec(query);assert(m,'Use SELECT columns FROM dataset [WHERE ...] [GROUP BY column] [ORDER BY column DESC] [LIMIT n]');const [,select,table,tail]=m;assert(tables[table],`Unknown dataset ${table}`);let rows=tables[table].map(r=>({...r}));
 const clauses={};const tokens=tokenize(tail.replace(/;\s*$/,''));let depth=0,starts=[];for(let i=0;i<tokens.length;i++){const t=tokens[i];if(t.value==='(')depth++;if(t.value===')')depth--;if(depth||t.type!=='id')continue;const k=String(t.value).toLowerCase();if(['where','limit'].includes(k))starts.push({key:k,start:t.start,end:t.end});if(['group','order'].includes(k)&&String(tokens[i+1]?.value).toLowerCase()==='by')starts.push({key:k,start:t.start,end:tokens[++i].end});}for(let i=0;i<starts.length;i++)clauses[starts[i].key]=tail.slice(starts[i].end,starts[i+1]?.start??tail.length).trim().replace(/;$/,'');if(tail.trim()&&(!starts.length||tail.slice(0,starts[0].start).trim()))throw Error('Unsupported SQL clause');assert(new Set(starts.map(s=>s.key)).size===starts.length,'Duplicate SQL clause');if(clauses.group)assert(/^[\w]+$/.test(clauses.group),'GROUP BY supports one field');if(clauses.where)rows=rows.filter(compileExpression(clauses.where));
 const columns=splitExpressions(select);const measures=columns.filter(s=>/^(count|sum|avg|min|max)\(/i.test(s)).map(s=>{const a=/^(count|sum|avg|min|max)\(\s*(\*|\w+)\s*\)(?:\s+as\s+(\w+))?$/i.exec(s);assert(a,'Invalid aggregate');return {op:a[1].toLowerCase(),column:a[2],as:a[3]||a[1].toLowerCase()};});
 if(measures.length||clauses.group)rows=aggregate(rows,clauses.group,measures.length?measures:undefined);
 else if(select.trim()!=='*'){const compiled=columns.map(s=>{const parts=s.split(/\s+as\s+/i);return {name:parts[1]||parts[0],fn:compileExpression(parts[0])};});rows=rows.map(r=>Object.fromEntries(compiled.map(c=>[c.name,c.fn(r)])));}
 if(clauses.order){const o=/^(\w+)(?:\s+(asc|desc))?$/i.exec(clauses.order);assert(o,'Invalid ORDER BY');rows.sort((a,b)=>((a[o[1]]>b[o[1]])?1:(a[o[1]]<b[o[1]])?-1:0)*(o[2]?.toLowerCase()==='desc'?-1:1));}
 if(clauses.limit){assert(/^\d+$/.test(clauses.limit),'Invalid LIMIT');rows=rows.slice(0,+clauses.limit);}return rows;
}
export function runPipeline(pipeline,datasets){
 const start=performance.now(),byId=new Map(pipeline.nodes.map(n=>[n.id,n]));assert(byId.size===pipeline.nodes.length,'Duplicate pipeline node IDs');const memo=new Map(),active=new Set(),trace=[];const outputs=[];
 function evaluate(id){assert(byId.has(id),'Missing input node '+id);if(memo.has(id))return memo.get(id);assert(!active.has(id),'Pipeline contains a cycle');active.add(id);const node=byId.get(id),t=performance.now(),c=node.config||{},inputs=(node.inputs||[]).map(evaluate);let rows=inputs[0]||[];
 switch(node.type){case 'source':{const ds=datasets.find(d=>d.id===c.dataset);assert(ds,'Source dataset not found');rows=ds.rows.map(r=>({...r}));break;}case 'filter':rows=rows.filter(compileExpression(c.expression||'true'));break;case 'derive':{assert(c.column&&!['__proto__','constructor','prototype'].includes(c.column),'Invalid derived column');const fn=compileExpression(c.expression||'0');rows=rows.map(r=>({...r,[c.column]:fn(r)}));break;}case 'select':rows=rows.map(r=>Object.fromEntries((c.columns||'').split(',').map(s=>s.trim()).filter(Boolean).map(k=>[k,r[k]])));break;case 'sort':rows=[...rows].sort((a,b)=>(a[c.column]>b[c.column]?1:a[c.column]<b[c.column]?-1:0)*(c.desc?-1:1));break;case 'aggregate':rows=aggregate(rows,c.group,[{column:c.column||'*',op:c.op||'count',as:c.as||'value'}]);break;case 'join':{assert(inputs.length===2,'Join needs two inputs');const lookup=groupBy(inputs[1],c.rightKey);rows=rows.flatMap(l=>{const matches=lookup.get(l[c.leftKey])||[];return matches.length?matches.map(r=>({...l,...Object.fromEntries(Object.entries(r).map(([k,v])=>[Object.hasOwn(l,k)?`right_${k}`:k,v]))})):c.how==='left'?[l]:[];});break;}case 'deduplicate':{const seen=new Set();rows=rows.filter(r=>{const k=c.column?r[c.column]:JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true;});break;}case 'output':outputs.push({name:c.name||node.name,rows,node:id});break;default:throw Error('Unsupported pipeline block: '+node.type);}
 active.delete(id);memo.set(id,rows);trace.push({id,name:node.name,type:node.type,rows:rows.length,duration:performance.now()-t,status:'success'});return rows;}
 for(const n of pipeline.nodes)evaluate(n.id);return {outputs,trace,duration:performance.now()-start,rows:outputs.at(-1)?.rows||memo.get(pipeline.nodes.at(-1)?.id)||[]};
}
