import {escapeHTML,uid,assert} from './utils.js';
import {buildDiagramScene} from '../render/primitives.js';
import {classifyTag,extractTagsFromText} from './analysis.js';
export function exportSVG(diagram){const s=buildDiagramScene(diagram);const metadata=escapeHTML(JSON.stringify({...diagram,revisions:[]}));const shapes=s.shapes.map(p=>p.kind==='polygon'?`<polygon points="${p.points.map(a=>a.join(',')).join(' ')}" fill="${p.color}"/>`:`<polyline points="${p.points.map(a=>a.join(',')).join(' ')}" fill="none" stroke="${p.color}" stroke-width="${p.width}" ${p.dash?'stroke-dasharray="5 5"':''}/>`).join('\n');const labels=s.labels.map(l=>`<text x="${l.x}" y="${l.y}" font-family="Arial,sans-serif" font-size="${l.size||12}" font-weight="${l.weight||400}" text-anchor="${l.align==='left'?'start':l.align==='right'?'end':'middle'}" fill="${l.color||'#526275'}">${escapeHTML(l.text)}</text>`).join('\n');return `<svg xmlns="http://www.w3.org/2000/svg" width="${diagram.width}" height="${diagram.height}" viewBox="0 0 ${diagram.width} ${diagram.height}"><metadata id="stratum-diagram">${metadata}</metadata><rect width="100%" height="100%" fill="white"/>${diagram.background?`<image width="${diagram.width}" height="${diagram.height}" href="${escapeHTML(diagram.background.data)}"/>`:''}${shapes}${labels}</svg>`;}
export function importSVG(text){assert(text.length<30*1024*1024,'SVG exceeds 30 MB');const doc=new DOMParser().parseFromString(text,'image/svg+xml');assert(!doc.querySelector('parsererror'),'Invalid SVG document');const metadata=doc.querySelector('metadata#stratum-diagram');if(metadata){const d=JSON.parse(metadata.textContent);assert(Array.isArray(d.nodes)&&Array.isArray(d.edges),'Invalid embedded model');d.id=uid('diagram');d.revisions=[];return d;}
 // Never attach untrusted SVG to the document. Strip active/external content before rasterization.
 doc.querySelectorAll('script,foreignObject,iframe,object,embed,style,animate,animateTransform,set').forEach(e=>e.remove());for(const e of doc.querySelectorAll('*'))for(const a of [...e.attributes]){if(/^on/i.test(a.name)||/href$/i.test(a.name)||/url\s*\(/i.test(a.value)||a.name==='style')e.removeAttribute(a.name);}
 const root=doc.documentElement,vb=(root.getAttribute('viewBox')||'').split(/[ ,]+/).map(Number);const width=parseFloat(root.getAttribute('width'))||vb[2]||1360,height=parseFloat(root.getAttribute('height'))||vb[3]||770;assert(width>0&&height>0&&width<=16000&&height<=16000,'SVG dimensions must be 1–16,000');const nodes=[];for(const el of doc.querySelectorAll('text')){const tags=extractTagsFromText(el.textContent);for(const tag of tags){const x=parseFloat(el.getAttribute('x')),y=parseFloat(el.getAttribute('y'));if(!Number.isFinite(x)||!Number.isFinite(y))continue;nodes.push({id:uid('node'),tag,name:tag,type:classifyTag(tag),x,y,rotation:0,status:'review',source:'SVG text candidate (transforms not interpreted)',notes:'Candidate located at the text coordinate, not a confirmed symbol position.',boxWidth:70,boxHeight:45});}}
 const clean=new XMLSerializer().serializeToString(root);return {id:uid('diagram'),number:'IMPORTED-SVG',name:'Imported engineering drawing',revision:'A',description:'Review candidate positions and all connectivity.',width,height,nodes,edges:[],revisions:[],background:{name:'Imported SVG',data:'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(clean)))}};
}
export async function imageFile(file){assert(file.size<=30*1024*1024,'Image exceeds 30 MB');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Cannot decode image'));img.src=data;});const scale=Math.min(1,6000/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return {id:uid('diagram'),name:file.name.replace(/\.[^.]+$/,''),number:'IMPORTED-IMAGE',revision:'A',description:'Raster source — annotate manually or use a configured vision endpoint.',width:c.width,height:c.height,nodes:[],edges:[],revisions:[],background:{name:file.name,data:c.toDataURL('image/png')}};}
