import {createSeed,SYMBOLS} from './core/seed.js';
import {Store,validateWorkspace} from './core/store.js';
import {uid,clone,escapeHTML as e,download,now,number,assert,normTag,safeURL} from './core/utils.js';
import {parseCSV,toCSV,profile,runPipeline,executeQuery,compileExpression} from './core/data.js';
import {validateDiagram,reconcileBOM,traceNetwork,stagePublish,applyApproval,validateVisionResult,diffDiagrams} from './core/analysis.js';
import {localAnswer,remoteAnswer,runEvaluations,callModel,analyzeImage} from './core/agent.js';
import {exportSVG,importSVG,imageFile} from './core/interchange.js';
import {WorkerClient} from './core/worker-client.js';
import {gpu} from './render/gpu.js';
import {Renderer} from './render/renderer.js';
import {Scene,palette} from './render/primitives.js';
import {DiagramEditor} from './render/editor.js';
import {icon} from './ui/icons.js';
import {button as b,ib,badge,field,selectField,table,notice,chart,empty} from './ui/components.js';
import {shell,routes,renderView,inspectorView,findingsRows,componentTable,objectTable,ontologyObjectInfo,chatMessages,chatCompose} from './ui/views.js';

class StratumApp {
 constructor(store){this.store=store;this.worker=new WorkerClient();this.ui={route:location.hash.slice(1)||'pid',pidTab:'drawing',ontologyTab:'graph',dataset:'ds-assets',dataPage:0,pipeline:'pipe-1',pipelineNode:'step-source',selected:'p101a',selectedEdge:null,modelMode:'local',thread:null,chatBusy:false,apiKey:'',drawer:false};this.editor=null;this.graph=null;this.modalSubmit=null;this.graphPositions=new Map();this.runningAutomations=false;}
 async start(){this.ui.thread=this.store.state.threads.at(-1)?.id||null;this.ui.route=routes.some(r=>r[0]===this.ui.route)?this.ui.route:'pid';document.documentElement.dataset.theme=this.store.state.theme;document.querySelector('#app').innerHTML=shell(this.store.state,this.ui);this.main=document.querySelector('#main');this.modal=document.querySelector('#modal');document.addEventListener('click',ev=>this.click(ev));document.addEventListener('submit',ev=>this.submit(ev));document.addEventListener('change',ev=>this.change(ev));document.addEventListener('input',ev=>this.input(ev));document.addEventListener('keydown',ev=>this.key(ev));window.addEventListener('hashchange',()=>{this.ui.route=location.hash.slice(1)||'pid';this.render();});window.addEventListener('pagehide',()=>this.store.save());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.store.save();});this.store.addEventListener('change',ev=>this.storeChanged(ev));this.store.addEventListener('saved',()=>this.updateStatus());gpu.addEventListener('change',()=>this.updateStatus());this.render();this.updateStatus();gpu.init();window.stratum={app:this,store:this.store,gpu,version:'0.1.0'};if(this.store.saveError)this.toast('Local storage is unavailable. Export your work before closing this tab.','error');}
 get state(){return this.store.state;}
 get diagram(){return this.store.diagram;}
 get pipeline(){return this.state.pipelines.find(p=>p.id===this.ui.pipeline)||this.state.pipelines[0];}
 get dataset(){return this.state.datasets.find(d=>d.id===this.ui.dataset)||this.state.datasets[0];}
 toast(message,type='success'){const div=document.createElement('div');div.className='toast '+(type==='error'?'error':'');div.innerHTML=icon(type==='error'?'warning':'checkCircle',15)+`<span>${e(message)}</span>`;div.setAttribute('role',type==='error'?'alert':'status');div.title='Click to dismiss';div.addEventListener('click',()=>div.remove());const stack=document.querySelector('#toasts');stack.append(div);while(stack.children.length>3)stack.firstElementChild.remove();setTimeout(()=>div.remove(),type==='error'?9000:4500);}
 error(err){console.error(err);this.toast(err.message||String(err),'error');}
 updateStatus(){const saved=document.querySelector('#save-status');if(saved)saved.textContent=this.store.saveError?'Storage error — export a backup':!this.store.db?'Session only — export to save':this.store.savedRevision===this.store.revision?'All changes saved locally':'Saving locally…';const engine=document.querySelector('#engine-status');if(engine)engine.textContent=`${gpu.mode} · on-demand rendering`;const role=document.querySelector('#role-status');if(role)role.textContent=`${this.state.settings.role} · local workspace`;}
 navigate(route){this.closeDrawer();if(this.modal.open)this.closeModal();if(location.hash==='#'+route){this.ui.route=route;this.render();}else location.hash=route;}
 render(){const stats=document.querySelector('#draw-stats');if(stats)stats.textContent='';this.pipelineAbort?.abort();if(this.editor){this.ui.canvasView={...this.editor.renderer.view};this.editor.destroy();this.editor=null;}this.graph?.destroy();this.graph=null;this.graphAbort?.abort();document.documentElement.dataset.theme=this.state.theme;const workspaceLabel=document.querySelector('.workspace-switch strong');if(workspaceLabel)workspaceLabel.textContent=this.state.name;document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===this.ui.route));const crumb=document.querySelector('#route-crumb');if(crumb)crumb.textContent=routes.find(r=>r[0]===this.ui.route)?.[1]||'Workspace';document.title=`Stratum Intelligence · ${routes.find(r=>r[0]===this.ui.route)?.[1]||'Workspace'}`;this.main.innerHTML=renderView(this.ui.route,this.state,this.ui,this.diagram,gpu);if(this.ui.route==='pid'&&this.ui.pidTab==='drawing')this.mountEditor();if(this.ui.route==='ontology'&&this.ui.ontologyTab==='graph')this.mountGraph();if(this.ui.route==='pipelines')this.mountPipeline();if(this.ui.route==='agents'){this.closeDrawer();this.scrollChat();}this.updateStatus();}
 mountPipeline(){
  const board=document.querySelector('.flow-board');if(!board)return;
  const controller=this.pipelineAbort=new AbortController();let drag=null;
  board.addEventListener('pointerdown',ev=>{
   const head=ev.target.closest('.flow-node-head');if(!head||this.state.settings.role==='viewer')return;
   const el=head.closest('.flow-node'),node=this.pipeline.nodes.find(n=>n.id===el.dataset.id);
   if(!node)return;head.setPointerCapture(ev.pointerId);drag={node,el,x:ev.clientX,y:ev.clientY,startX:node.x,startY:node.y,nextX:node.x,nextY:node.y,moved:false};
  },{signal:controller.signal});
  board.addEventListener('pointermove',ev=>{
   if(!drag)return;const dx=ev.clientX-drag.x,dy=ev.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)<4&&!drag.moved)return;
   drag.moved=true;drag.nextX=Math.max(10,Math.round((drag.startX+dx)/10)*10);drag.nextY=Math.max(10,Math.round((drag.startY+dy)/10)*10);
   drag.el.style.left=drag.nextX+'px';drag.el.style.top=drag.nextY+'px';
   const pos=n=>n.id===drag.node.id?{x:drag.nextX,y:drag.nextY}:n;
   board.querySelector('svg').innerHTML=this.pipeline.nodes.flatMap(node=>(node.inputs||[]).map(id=>{const source=this.pipeline.nodes.find(n=>n.id===id);if(!source)return '';const a=pos(source),b=pos(node);return `<path d="M${a.x+214} ${a.y+30} C${a.x+248} ${a.y+30} ${b.x-40} ${b.y+30} ${b.x} ${b.y+30}" stroke="#9baec5" fill="none" stroke-width="1.5"/>`;})).join('');
  },{signal:controller.signal});
  board.addEventListener('pointerup',()=>{if(!drag)return;const d=drag;drag=null;if(d.moved){try{this.store.transact('Move pipeline block',()=>Object.assign(d.node,{x:d.nextX,y:d.nextY}));this.ui.pipelineNode=d.node.id;this.render();}catch(e){this.error(e);this.render();}}},{signal:controller.signal});
  board.addEventListener('pointercancel',()=>{if(drag){drag=null;this.render();}},{signal:controller.signal});
 }
 mountEditor(){const view=this.ui.canvasView;this.editor=new DiagramEditor(document.querySelector('#drawing-stage'),this.store,{onSelect:selection=>{this.ui.selectedEdge=typeof selection==='object'&&selection?selection.edge:null;this.ui.selected=this.ui.selectedEdge?null:selection;this.updateInspector();},onChange:info=>{if(info.zoom){const z=document.querySelector('#zoom-label');if(z)z.textContent=Math.round(info.zoom*100)+'%';}if(info.tool)document.querySelectorAll('[data-action=tool]').forEach(el=>el.classList.toggle('active',el.dataset.value===info.tool));},onStats:stats=>{const el=document.querySelector('#draw-stats');if(el)el.textContent=`${number(stats.duration,1)} ms CPU frame · ${stats.mode==='WebGPU'?number(stats.vertices)+' GPU vertices':number(stats.primitives)+' Canvas primitives'}`;},onError:err=>this.error(err)});this.editor.selection=this.ui.selected;this.editor.selectedEdge=this.ui.selectedEdge;this.editor.refresh();if(view)requestAnimationFrame(()=>{this.editor?.renderer.setView(view);const z=document.querySelector('#zoom-label');if(z)z.textContent=Math.round(view.scale*100)+'%';});}
 updateInspector(){const inspector=document.querySelector('#inspector');if(inspector)inspector.innerHTML=inspectorView(this.state,this.ui,this.diagram);}
 refreshDiagram(){this.editor?.refresh();this.updateInspector();const findings=validateDiagram(this.diagram),list=document.querySelector('#finding-list');if(list)list.innerHTML=findingsRows(findings);const count=document.querySelector('#findings-count');if(count)count.textContent=findings.length;}
 storeChanged(ev){this.updateStatus();if(this.ui.route==='pid')this.refreshDiagram();if(!this.runningAutomations&&/component|Connect|drawing|connection/i.test(ev.detail.label)&&!/^Undo|^Redo/.test(ev.detail.label)){const enabled=this.state.automations.filter(a=>a.enabled&&a.trigger==='diagram.change');if(enabled.length)queueMicrotask(()=>{this.runningAutomations=true;try{for(const a of enabled)this.runAutomation(a.id,false);}finally{this.runningAutomations=false;}});}}
 showModal(title,body,{submit='Save',onSubmit=null,wide=false,footer=''}={}){this.modal.className=wide?'wide':'';this.modal.innerHTML=`<form data-form="modal"><div class="modal-head"><h2>${e(title)}</h2>${ib('Close dialog','close-modal','x')}</div><div class="modal-body">${body}</div><div class="modal-error" id="modal-error"></div><div class="modal-footer">${footer}${b(submit?'Cancel':'Close','close-modal')}${submit?`<button class="btn primary" type="submit">${e(submit)}</button>`:''}</div></form>`;this.modalSubmit=onSubmit;if(!this.modal.open)this.modal.showModal();queueMicrotask(()=>this.modal.querySelector('input:not([type=hidden]),textarea,select')?.focus());}
 closeModal(){this.modal.close();this.modalSubmit=null;}
 async click(ev){const target=ev.target.closest('[data-action],[data-route]');if(!target||target.disabled)return;if(target.dataset.route){ev.preventDefault();this.navigate(target.dataset.route);return;}if(target.closest('form')&&target.tagName==='BUTTON'&&!target.hasAttribute('type'))ev.preventDefault();try{await this.action(target.dataset.action,target);}catch(err){this.error(err);}}
 async action(action,el){const id=el?.dataset.id,v=el?.dataset.value;switch(action){
 case 'tab':this.ui[el.dataset.scope==='pid'?'pidTab':'ontologyTab']=v;this.render();break;
 case 'go-pid':case 'go-observability':case 'go-settings':case 'go-logic':this.navigate(action.slice(3));break;
 case 'close-modal':this.closeModal();break;
 case 'mobile-inspector':document.querySelector('.pid-workspace')?.classList.toggle('inspector-open');break;
 case 'theme':this.store.transact('Change theme',s=>s.theme=s.theme==='dark'?'light':'dark',{edit:false,history:false});this.render();break;
 case 'workspace':this.showModal('Northline workspace',`<p>Your workspace lives in this browser. Export a backup to move it between devices.</p>${field('Workspace name','name',this.state.name,'text','required')}<div class="actions mt">${b('Export workspace','export-workspace','download')}${b('Import workspace','import-workspace','upload')}</div>`,{onSubmit:f=>{this.store.transact('Rename workspace',s=>s.name=f.get('name'));this.render();}});break;
 case 'search':this.searchModal();break;
 case 'help':this.help();break;
 case 'notifications':this.navigate('governance');break;
 case 'undo':this.store.undo()?this.toast('Last change undone'):this.toast('No changes to undo');this.render();break;
 case 'redo':this.store.redo()?this.toast('Change restored'):this.toast('No changes to redo');this.render();break;
 case 'tool':this.editor?.setTool(v);break;
 case 'zoom-in':this.editor?.zoom(1.22);break;
 case 'zoom-out':this.editor?.zoom(1/1.22);break;
 case 'fit':this.editor?.fit();break;
 case 'rotate':this.editor?.rotate();break;
 case 'duplicate':this.editor?.duplicate();break;
 case 'delete-selection':if(this.editor)this.editor.remove();break;
 case 'clear-selection':this.editor?.select(null);break;
 case 'select-diagram':this.store.transact('Select drawing',s=>s.activeDiagram=id,{edit:false,history:false});this.ui.selected=this.diagram.nodes[0]?.id||null;this.ui.selectedEdge=null;this.ui.canvasView=null;this.editor?.destroy();this.editor=null;this.render();break;
 case 'new-drawing':this.newDrawing();break;
 case 'symbol-library':this.showModal('Engineering symbol library',`<p>Select a symbol and click the drawing to place it.</p><div class="three-col">${Object.entries(SYMBOLS).map(([key,d])=>`<button type="button" class="symbol-button" data-action="choose-symbol" data-value="${key}">${icon(key==='control'||key==='check'?'valve':key,25)}${e(d.label)}</button>`).join('')}</div>`,{submit:null});break;
 case 'choose-symbol':this.closeModal();this.editor?.setTool('add:'+v);break;
 case 'add-component':this.componentModal();break;
 case 'verify-component':case 'unverify-component':{const n=this.diagram.nodes.find(n=>n.id===this.ui.selected);if(n){this.store.transact(action==='verify-component'?'Verify component':'Flag component for review',()=>n.status=action==='verify-component'?'verified':'review');this.toast(n.status==='verified'?`${n.tag} marked verified`:`${n.tag} marked for review`);}break;}
 case 'focus-component':case 'focus-finding':if(id){this.ui.pidTab='drawing';this.ui.selected=id;this.ui.selectedEdge=null;if(this.ui.route!=='pid'){this.navigate('pid');setTimeout(()=>this.editor?.focus(id),80);}else if(!this.editor){this.render();requestAnimationFrame(()=>this.editor?.focus(id));}else this.editor.focus(id);}else this.toast('This finding applies to the drawing or an invalid endpoint.');break;
 case 'validate':this.validationModal();break;
 case 'trace':this.traceModal();break;
 case 'object-from-component':{const obj=this.state.objects.find(o=>o.diagramNode===id);if(!obj)throw Error('This component is not in the ontology. Publish it through the review workflow first.');this.ui.objectSelected=obj.id;this.ui.ontologyTab='graph';this.navigate('ontology');break;}
 case 'import-drawing':await this.pickFile('.json,.svg,.png,.jpg,.jpeg,.webp,.pdf',file=>this.importDrawing(file));break;
 case 'import-workspace':await this.pickFile('.json',async f=>{const state=JSON.parse(await f.text());validateWorkspace(state);this.showModal('Replace current workspace?',`<p>This imports <strong>${e(state.name)}</strong> with ${state.objects.length} objects and ${state.diagrams.length} drawings. Export your existing workspace first to keep a separate backup.</p>`,{submit:'Import workspace',onSubmit:()=>{this.store.replace(state);this.ui.canvasView=null;this.ui.selected=this.diagram.nodes[0]?.id;this.ui.dataset=this.state.datasets[0]?.id;this.render();this.toast('Workspace imported');}});});break;
 case 'export-workspace':download('stratum-workspace.json',JSON.stringify(this.state,null,2));this.toast('Workspace backup exported; API key excluded');break;
 case 'export-drawing':this.exportDrawingModal();break;
 case 'export-svg':download(`${this.diagram.number}.svg`,exportSVG(this.diagram),'image/svg+xml');this.closeModal();break;
 case 'export-png':{const renderer=this.editor?.renderer;if(!renderer)throw Error('Open the drawing canvas to export a PNG');const blob=await renderer.png(this.diagram.width,this.diagram.height);download(`${this.diagram.number}.png`,blob,'image/png');this.closeModal();break;}
 case 'export-diagram-json':download(`${this.diagram.number}.json`,JSON.stringify(this.diagram,null,2));this.closeModal();break;
 case 'export-components':download(`${this.diagram.number}-components.csv`,toCSV(this.diagram.nodes),'text/csv');break;
 case 'export-bom':download('bom-reconciliation.csv',toCSV(reconcileBOM(this.diagram,this.state.datasets.find(d=>d.id==='ds-bom')?.rows||[])),'text/csv');break;
 case 'save-revision':this.showModal('Save drawing revision',`<p>Save a complete component and connection baseline. Later edits can be compared or restored.</p>${field('Revision name','name',`Revision ${this.diagram.revision} · baseline ${this.diagram.revisions.length+1}`,'text','required')}`,{submit:'Save baseline',onSubmit:f=>{this.store.transact('Save drawing revision',()=>this.diagram.revisions.push({id:uid('revision'),name:f.get('name'),time:now(),snapshot:clone({...this.diagram,revisions:[]})}));this.render();this.toast('Revision baseline saved');}});break;
 case 'restore-revision':{const r=this.diagram.revisions.find(r=>r.id===id);assert(r,'Revision not found');this.showModal('Restore revision?',`<p>Restore <strong>${e(r.name)}</strong>. Current changes remain recoverable using Undo in this session.</p>`,{submit:'Restore',onSubmit:()=>{this.store.transact('Restore drawing revision',()=>{const revisions=this.diagram.revisions;Object.assign(this.diagram,clone(r.snapshot),{revisions});});this.render();}});break;}
 case 'publish':this.publishModal();break;
 case 'inspect-approval':{const a=this.state.approvals.find(a=>a.id===id);this.showModal(a.title,`<p>${e(a.summary)}</p><textarea class="json-editor" readonly>${e(JSON.stringify(a.payload,null,2))}</textarea>`,{submit:null,wide:true});break;}
 case 'approve':this.approvalModal(id);break;
 case 'reject':this.showModal('Reject proposed action',`<p>This does not change the ontology.</p>${field('Review note','note','','text','required')}`,{submit:'Reject action',onSubmit:f=>{this.store.transact('Reject proposed action',s=>{const a=s.approvals.find(a=>a.id===id);assert(a.status==='pending','Action is no longer pending');a.status='rejected';a.note=f.get('note');a.resolved=now();});this.render();}});break;
 case 'new-work-order':this.workOrderModal();break;
 case 'stage-object-edit':this.stageEditModal();break;
 case 'import-data':await this.pickFile('.csv,.json',f=>this.importDataset(f));break;
 case 'import-bom':await this.pickFile('.csv,.json',f=>this.importDataset(f,true));break;
 case 'select-dataset':this.ui.dataset=id;this.ui.dataPage=0;this.ui.queryResults=null;this.ui.queryText='';this.render();break;
 case 'run-query':await this.runQuery();break;
 case 'clear-query':this.ui.queryResults=null;this.ui.dataPage=0;this.render();break;
 case 'data-prev':this.ui.dataPage=Math.max(0,this.ui.dataPage-1);this.render();break;
 case 'data-next':this.ui.dataPage++;this.render();break;
 case 'profile-data':await this.profileData();break;
 case 'export-data':download(`${this.dataset.name}.csv`,toCSV(this.ui.queryResults||this.dataset.rows),'text/csv');break;
 case 'edit-cell':this.editCell(Number(el.dataset.row)+this.ui.dataPage*100,el.dataset.key);break;
 case 'add-row':this.rowModal();break;
 case 'add-document':this.documentModal();break;
 case 'view-document':this.documentModal(id);break;
 case 'new-object':this.objectModal();break;
 case 'edit-object':this.objectModal(id);break;
 case 'new-object-type':this.typeModal();break;
 case 'edit-type':this.typeModal(id);break;
 case 'new-link':this.linkModal();break;
 case 'export-ontology':download('stratum-ontology.json',JSON.stringify({objectTypes:this.state.objectTypes,objects:this.state.objects,links:this.state.links},null,2));break;
 case 'graph-fit':this.graph?.fit(1360,820,25);break;
 case 'new-pipeline':this.newPipeline();break;
 case 'select-block':this.ui.pipelineNode=id;this.render();break;
 case 'add-block':this.addBlockModal();break;
 case 'remove-block':this.store.transact('Remove pipeline block',()=>{this.pipeline.nodes=this.pipeline.nodes.filter(n=>n.id!==id);for(const n of this.pipeline.nodes)n.inputs=n.inputs.filter(x=>x!==id);});this.ui.pipelineNode=this.pipeline.nodes[0]?.id;this.render();break;
 case 'edit-pipeline-json':this.showModal('Edit pipeline definition',`<p>Source, filter, derive, select, sort, aggregate, join, deduplicate, and output blocks are supported. Invalid/cyclic definitions are rejected.</p><textarea name="definition" class="json-editor" spellcheck="false">${e(JSON.stringify(this.pipeline.nodes,null,2))}</textarea>`,{wide:true,onSubmit:f=>{const nodes=JSON.parse(f.get('definition'));assert(Array.isArray(nodes),'Expected node array');runPipeline({...this.pipeline,nodes},this.state.datasets);this.store.transact('Edit pipeline definition',()=>this.pipeline.nodes=nodes);this.ui.pipelineResult=null;this.render();}});break;
 case 'run-pipeline':await this.executePipeline();break;
 case 'materialize-pipeline':this.materializePipeline();break;
 case 'export-pipeline':download('pipeline-definition.json',JSON.stringify(this.pipeline,null,2));break;
 case 'new-thread':this.createThread();this.render();break;
 case 'select-thread':this.ui.thread=id;this.render();break;
 case 'configure-agent':this.agentModal();break;
 case 'chat-prompt':await this.sendChat(el.dataset.question);break;
 case 'ask':this.openDrawer();await this.sendChat(el.dataset.question||'Summarize the active drawing');break;
 case 'close-drawer':this.closeDrawer();break;
 case 'open-agent-studio':this.navigate('agents');break;
 case 'citation':this.citation(el.dataset.kind,id);break;
 case 'run-evals':await this.evaluations();break;
 case 'add-eval':this.evalModal();break;
 case 'edit-eval':this.evalModal(id);break;
 case 'export-evals':download('evaluation-results.json',JSON.stringify(this.state.evaluationRuns,null,2));break;
 case 'add-widget':this.widgetModal();break;
 case 'edit-widget':this.widgetModal(id);break;
 case 'remove-widget':this.store.transact('Remove dashboard widget',s=>s.dashboard=s.dashboard.filter(w=>w.id!==id));this.render();break;
 case 'move-widget':this.store.transact('Move dashboard widget',s=>{const i=s.dashboard.findIndex(w=>w.id===id);if(i>0)[s.dashboard[i-1],s.dashboard[i]]=[s.dashboard[i],s.dashboard[i-1]];});this.render();break;
 case 'new-automation':this.automationModal();break;
 case 'edit-automation':this.automationModal(id);break;
 case 'run-automation':this.runAutomation(id,true);break;
 case 'analyze-telemetry':await this.analyzeTelemetry();break;
 case 'engine-diagnostics':await this.engineDiagnostics();break;
 case 'export-audit':download('stratum-audit.json',JSON.stringify(this.state.audit,null,2));break;
 case 'export-approvals':download('stratum-approvals.json',JSON.stringify(this.state.approvals,null,2));break;
 case 'test-model':await this.testModel();break;
 case 'vision-analyze':await this.visionDialog();break;
 case 'reset-workspace':this.showModal('Reset sample workspace?',`<p>This replaces your workspace with the original sample. Export a backup before proceeding. Enter <strong>RESET</strong> to confirm.</p>${field('Confirmation','confirm','','text','required')}`,{submit:'Reset sample',onSubmit:f=>{assert(f.get('confirm')==='RESET','Type RESET to confirm');this.store.replace(createSeed());this.ui.selected='p101a';this.ui.dataset='ds-assets';this.ui.thread=null;this.ui.canvasView=null;this.ui.queryResults=null;this.ui.pipelineResult=null;this.ui.apiKey='';this.render();this.toast('Sample workspace restored');}});break;
 default:throw Error('Unknown command: '+action);
 }}
 async submit(ev){const form=ev.target.closest('form[data-form]');if(!form)return;ev.preventDefault();const data=new FormData(form),kind=form.dataset.form;try{
 if(kind==='modal'){const submit=form.querySelector('[type=submit]');if(submit)submit.disabled=true;try{await this.modalSubmit?.(data);this.closeModal();}finally{if(submit)submit.disabled=false;}return;}
 if(kind==='component'){const n=this.diagram.nodes.find(n=>n.id===data.get('id'));assert(n,'Component no longer exists');assert(data.get('tag').trim(),'Tag is required');assert(!this.diagram.nodes.some(other=>other.id!==n.id&&normTag(other.tag)===normTag(data.get('tag'))),'This tag already exists');this.store.transact('Edit component properties',()=>{n.tag=data.get('tag').trim();n.name=data.get('name').trim();n.type=data.get('type');n.lineClass=data.get('lineClass');for(const k of ['diameter','designPressure','operatingPressure']){const value=data.get(k);n[k]=value===''?null:Number(value);assert(value===''||Number.isFinite(n[k]),'Invalid numeric value');}if(['valve','control','check'].includes(n.type))n.closed=data.has('closed');});this.toast('Component properties saved');return;}
 if(kind==='edge'){const edge=this.diagram.edges.find(e=>e.id===data.get('id'));const points=JSON.parse(data.get('points')||'[]');assert(Array.isArray(points)&&points.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)),'Waypoints must be numeric [x,y] pairs');assert(data.get('from')!==data.get('to'),'Connection endpoints must be different');this.store.transact('Edit connection',()=>Object.assign(edge,{tag:data.get('tag'),from:data.get('from'),to:data.get('to'),kind:data.get('kind'),diameter:Number(data.get('diameter')),lineClass:data.get('lineClass'),points}));this.toast('Connection saved');return;}
 if(kind==='block'){const n=this.pipeline.nodes.find(n=>n.id===data.get('id'));assert(n,'Block not found');const config=Object.fromEntries([...data].filter(([k])=>!['id','blockName','inputs'].includes(k)));if(Object.hasOwn(config,'desc'))config.desc=config.desc==='true';if(config.expression)compileExpression(config.expression);const inputs=data.getAll('inputs');if(n.type!=='source')assert(inputs.length===(n.type==='join'?2:1),n.type==='join'?'A join needs exactly two inputs':'This block needs one input');this.store.transact('Edit pipeline block',()=>{n.name=data.get('blockName');n.config=config;n.inputs=inputs;runPipeline(this.pipeline,this.state.datasets);});this.ui.pipelineResult=null;this.render();this.toast('Pipeline block saved');return;}
 if(kind==='chat'){await this.sendChat(data.get('question'));form.reset();return;}
 if(kind==='settings'){this.ui.apiKey=data.get('apiKey')||'';const endpoint=data.get('endpoint').trim();if(endpoint)safeURL(endpoint);this.store.transact('Configure model connection',s=>{Object.assign(s.settings,{endpoint,model:data.get('model').trim(),visionModel:data.get('visionModel').trim(),shareContext:data.has('shareContext')});});this.toast('Connection settings saved; API key remains in memory');this.render();return;}
 if(kind==='preferences'){this.store.transact('Change workspace preferences',s=>{s.name=data.get('name');s.theme=data.get('theme');s.settings.role=data.get('role');},{edit:false,history:false});this.render();this.toast('Workspace preferences saved');return;}
 }catch(err){if(kind==='modal'){const el=document.querySelector('#modal-error');if(el)el.textContent=err.message;}else this.error(err);}}
 async change(ev){const el=ev.target;try{if(el.id==='layer-labels'){this.editor.showLabels=el.checked;this.editor.refresh();}if(el.id==='layer-signals'){this.editor.showSignals=el.checked;this.editor.refresh();}if(el.id==='layer-grid'){this.editor.renderer.grid=el.checked;this.editor.renderer.requestDraw();}if(el.id==='pipeline-select'){this.ui.pipeline=el.value;this.ui.pipelineNode=null;this.ui.pipelineResult=null;this.render();}if(el.id==='object-type-filter'){this.ui.objectType=el.value;this.render();}if(el.id==='assistant-mode'){this.ui.modelMode=el.value;if(el.value==='remote'&&(!this.state.settings.endpoint||!this.state.settings.shareContext))this.toast('External mode requires an endpoint and explicit context-sharing consent in Models & settings.','error');}if(el.dataset.automation){this.store.transact('Toggle automation',s=>s.automations.find(a=>a.id===el.dataset.automation).enabled=el.checked);this.render();}}catch(err){this.error(err);}}
 input(ev){const el=ev.target;if(el.id==='component-search'){this.ui.componentFilter=el.value;document.querySelector('#components-table').innerHTML=componentTable(this.diagram,this.ui);}if(el.id==='object-search'){this.ui.objectFilter=el.value;document.querySelector('#object-table').innerHTML=objectTable(this.state.objects.filter(o=>(!this.ui.objectType||o.type===this.ui.objectType)&&JSON.stringify(o).toLowerCase().includes(el.value.toLowerCase())));}if(el.id==='command-input')this.searchResults(el.value);if(el.id==='sql-query')this.ui.queryText=el.value;}
 key(ev){const typing=/INPUT|TEXTAREA|SELECT/.test(ev.target.tagName)||ev.target.isContentEditable;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='k'){ev.preventDefault();this.searchModal();return;}if(ev.key==='Enter'&&ev.target.id==='chat-input'&&!ev.shiftKey){ev.preventDefault();if(ev.target.value.trim())this.sendChat(ev.target.value.trim()).catch(e=>this.error(e));return;}if(typing||this.modal.open)return;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();try{ev.shiftKey?this.store.redo():this.store.undo();this.render();}catch(e){this.error(e);}}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='s'){ev.preventDefault();this.store.save().then(saved=>this.toast(saved?'Saved locally':'Storage unavailable — export a workspace backup',saved?'success':'error'));}if(ev.key==='Escape')this.closeDrawer();if(ev.key==='Enter'&&ev.target.dataset.action)ev.target.click();}
 async pickFile(accept,handler){const input=document.createElement('input');input.type='file';input.accept=accept;input.hidden=true;document.body.append(input);input.addEventListener('change',async()=>{try{if(input.files[0])await handler(input.files[0]);}catch(e){this.error(e);}finally{input.remove();}},{once:true});input.addEventListener('cancel',()=>input.remove(),{once:true});input.click();}
 newDrawing(){this.showModal('Create engineering drawing',`${field('Drawing name','name','Untitled process diagram','text','required')}${field('Drawing number','number',`PID-${String(this.state.diagrams.length+1).padStart(3,'0')}`,'text','required')}<div class="form-grid">${field('Width','width',1360,'number','min="200" max="16000"')}${field('Height','height',770,'number','min="200" max="16000"')}</div>`,{submit:'Create drawing',onSubmit:f=>{const d={id:uid('diagram'),name:f.get('name'),number:f.get('number'),description:'New local engineering drawing',revision:'A',width:Number(f.get('width')),height:Number(f.get('height')),nodes:[],edges:[],revisions:[],background:null};this.store.transact('Create drawing',s=>{s.diagrams.push(d);s.activeDiagram=d.id;});this.ui.canvasView=null;this.ui.selected=null;this.ui.pidTab='drawing';this.editor?.destroy();this.editor=null;this.render();}});}
 componentModal(){this.showModal('Add diagram component',`${selectField('Symbol type','type',Object.entries(SYMBOLS).map(([k,v])=>[k,v.label]),'pump')}${field('Tag','tag','P-201','text','required')}${field('Description','name','New equipment','text','required')}<div class="form-grid">${field('X coordinate','x',Math.round(this.diagram.width/2),'number','step="any"')}${field('Y coordinate','y',Math.round(this.diagram.height/2),'number','step="any"')}</div>`,{submit:'Add component',onSubmit:f=>{assert(!this.diagram.nodes.some(n=>normTag(n.tag)===normTag(f.get('tag'))),'Tag already exists');const n={id:uid('node'),tag:f.get('tag'),name:f.get('name'),type:f.get('type'),x:Number(f.get('x')),y:Number(f.get('y')),rotation:0,status:'review',source:'Manual annotation',diameter:100,lineClass:'CS150',operatingPressure:0,designPressure:16,temperature:20};this.store.transact('Add diagram component',()=>this.diagram.nodes.push(n));this.ui.selected=n.id;this.ui.selectedEdge=null;this.ui.pidTab='drawing';if(this.ui.route==='pid'){this.render();requestAnimationFrame(()=>this.editor?.focus(n.id));}else this.navigate('pid');}});}
 validationModal(){const findings=validateDiagram(this.diagram);this.showModal('Diagram validation report',`<p>${this.diagram.nodes.length} components and ${this.diagram.edges.length} connections checked. ${findings.length} findings require review.</p>${table(findings,[{key:'tag',label:'Tag'},{key:'severity',label:'Severity',render:v=>badge(v,v)},{key:'title',label:'Finding'},{key:'detail',label:'Evidence'}])}<div class="mt">${notice('Checks cover tags, endpoints, disconnected components, control signals, stored pressure limits, and line sizes. This is not a HAZOP, hydraulic simulation, certified design check, or safety review.','warning')}</div>`,{submit:null,wide:true});this.store.transact('Run diagram checks',s=>s.runs.push({id:uid('run'),name:'Diagram validation',kind:'validation',time:now(),status:'success',summary:`${findings.length} findings`,duration:0}),{edit:false,history:false});}
 traceModal(){this.showModal('Trace process connectivity',`${selectField('Start component','start',this.diagram.nodes.map(n=>[n.id,`${n.tag} — ${n.name}`]),this.ui.selected||this.diagram.nodes[0]?.id)}${selectField('Trace direction','direction',[['downstream','Downstream'],['upstream','Upstream'],['both','Impact / both directions']],'downstream')}<label class="checkbox-label mb"><input name="respectClosed" type="checkbox" checked>Stop traversal at closed valves</label><label class="checkbox-label mb"><input name="signals" type="checkbox">Include instrument signal links</label>${notice('This traverses the stored graph. It does not establish a safe isolation boundary or account for physical flow, leakage, inventories, or relief paths.','warning')}`,{submit:'Trace graph',onSubmit:f=>{const r=traceNetwork(this.diagram,f.get('start'),{direction:f.get('direction'),respectClosed:f.has('respectClosed'),signals:f.has('signals')});if(this.editor){this.editor.highlight=new Set([...r.nodes,...r.edges]);this.editor.refresh();}this.toast(`Traced ${r.nodes.length} connected components and ${r.edges.length} links`);}});}
 async importDrawing(file){this.store.checkEdit();const ext=file.name.toLowerCase().split('.').at(-1);let d;if(ext==='pdf'){this.toast('Loading optional PDF parser…');const {loadPDF,importPDFPage}=await import('./core/pdf-import.js');const pdf=await loadPDF(file);this.modal.addEventListener('close',()=>pdf.document.destroy(),{once:true});this.showModal('Import a PDF page',`<p>${e(file.name)} · ${pdf.document.numPages} pages. Embedded text yields tag candidates; scanned pages require annotation or a configured vision model.</p>${field('Page number','page',1,'number',`min="1" max="${pdf.document.numPages}" required`)}`,{submit:'Import page',onSubmit:async f=>{this.addDiagram(await importPDFPage(pdf,Number(f.get('page'))));}});return;}if(ext==='svg')d=importSVG(await file.text());else if(ext==='json'){const data=JSON.parse(await file.text());if(data.schemaVersion===1){validateWorkspace(data);this.showModal('Import workspace file?',`<p>This JSON contains a complete workspace. Replace the current local workspace with <strong>${e(data.name)}</strong>?</p>`,{submit:'Import workspace',onSubmit:()=>{this.store.replace(data);this.ui.canvasView=null;this.render();}});return;}d=data;assert(Array.isArray(d.nodes)&&Array.isArray(d.edges),'Expected diagram nodes[] and edges[]');d={width:1360,height:770,revision:'A',name:file.name,number:'IMPORTED-JSON',background:null,...d,id:uid('diagram'),revisions:[]};}else d=await imageFile(file);this.addDiagram(d);}
 addDiagram(d){this.store.transact('Import engineering drawing',s=>{s.diagrams.push(d);s.activeDiagram=d.id;});this.ui.selected=d.nodes[0]?.id||null;this.ui.selectedEdge=null;this.ui.canvasView=null;this.ui.pidTab='drawing';this.editor?.destroy();this.editor=null;if(this.ui.route!=='pid')this.navigate('pid');else this.render();this.toast(`Imported ${d.nodes.length} component candidates. Review before publication.`);}
 exportDrawingModal(){this.showModal('Export engineering drawing',`<p>SVG exports include an editable Stratum model in metadata. JSON preserves the full drawing. PNG renders the current drawing as a high-resolution image.</p><div class="stack">${b('Editable SVG + model metadata','export-svg','pid','wide')}${b('PNG image','export-png','download','wide',this.editor?'':'disabled')}${b('Native diagram JSON','export-diagram-json','code','wide')}${b('Component register CSV','export-components','table','wide')}</div>`,{submit:null});}
 publishModal(){const findings=validateDiagram(this.diagram);this.showModal('Prepare ontology publication',`<p>Stage <strong>${this.diagram.nodes.length} components</strong> and <strong>${this.diagram.edges.length} connections</strong> from ${e(this.diagram.number)}. The staged snapshot will not change when the drawing is edited later.</p>${findings.length?notice(`${findings.length} structural findings remain. Unverified components publish with “Needs review” status. Review them before approving this change.`,'warning'):notice('No findings from the implemented structural rules. A human review is still required.')}<div class="quick-path mt"><span>Drawing snapshot</span>${icon('arrow',13)}<span>Review queue</span>${icon('arrow',13)}<span>Ontology upsert</span></div>`,{submit:'Stage for review',onSubmit:()=>{this.store.transact('Stage ontology publication',s=>s.approvals.push(stagePublish(this.diagram)));this.toast('Publication staged. Review it in Governance or Logic & actions.');this.render();}});}
 approvalModal(id){const a=this.state.approvals.find(a=>a.id===id);assert(a?.status==='pending','This action is no longer pending');this.showModal('Approve proposed change?',`<p><strong>${e(a.title)}</strong></p><p>${e(a.summary||'This will modify the local ontology.')}</p><textarea class="json-editor" readonly style="min-height:170px">${e(JSON.stringify(a.payload,null,2))}</textarea><div class="mt">${notice('Approval applies only to this local workspace. No external system or equipment will be operated.')}</div>`,{submit:'Approve and apply',wide:true,onSubmit:()=>{this.store.transact('Approve and apply action',s=>applyApproval(s,id));this.render();this.toast('Approved change applied to the local ontology');}});}
 workOrderModal(){this.showModal('Prepare engineering work order',`${field('Work order title','name','Review process component','text','required')}${selectField('Linked asset','asset',this.state.objects.filter(o=>o.type!=='Work order').map(o=>[o.id,`${o.tag} — ${o.name}`]),'asset-'+this.ui.selected)}${selectField('Priority','priority',['Low','Medium','High'],'Medium')}<label class="form-field"><span>Engineering notes</span><textarea name="notes" rows="4" required>Review the source drawing and confirm component configuration.</textarea></label>`,{submit:'Stage work order',onSubmit:f=>{const payload={...Object.fromEntries(f),tag:'WO-'+String(this.state.objects.filter(o=>o.type==='Work order').length+this.state.approvals.filter(a=>a.kind==='work-order').length+1).padStart(4,'0')};this.store.transact('Stage work order',s=>s.approvals.push({id:uid('approval'),kind:'work-order',title:payload.name,status:'pending',created:now(),payload,summary:`Create ${payload.tag} linked to ${s.objects.find(o=>o.id===payload.asset)?.tag}. Priority: ${payload.priority}.`}));this.render();this.toast('Work order staged for review');}});}
 stageEditModal(){this.showModal('Propose ontology property change',`${selectField('Object','object',this.state.objects.map(o=>[o.id,`${o.tag} — ${o.name}`]),this.ui.objectSelected||this.state.objects[0]?.id)}${field('Property name','property','status','text','required')}${field('New value','value','Needs review','text','required')}`,{submit:'Stage proposed change',onSubmit:f=>{const id=f.get('object'),property=f.get('property');assert(!['id','__proto__','constructor','prototype'].includes(property),'This property cannot be changed');const o=this.state.objects.find(o=>o.id===id);this.store.transact('Stage object property change',s=>s.approvals.push({id:uid('approval'),kind:'object-edit',title:`Update ${o.tag} · ${property}`,created:now(),status:'pending',summary:`Change ${property} from “${o[property]??'unset'}” to “${f.get('value')}”.`,payload:{id,changes:{[property]:f.get('value')},before:{[property]:o[property]}}}));this.render();}});}
 async importDataset(file,bom=false){assert(file.size<=50*1024*1024,'Dataset exceeds 50 MB');const text=await file.text();let rows=file.name.toLowerCase().endsWith('.csv')?await this.worker.call('parseCSV',text):JSON.parse(text);if(rows.rows)rows=rows.rows;assert(Array.isArray(rows)&&rows.every(r=>r&&typeof r==='object'&&!Array.isArray(r)),'Expected an array of record objects');assert(rows.length<=500000,'Import limit: 500,000 records');if(bom)assert(rows.every(r=>Object.hasOwn(r,'tag')),'BOM records must include a tag column');this.showModal(bom?'Import bill of materials':'Import dataset',`<p>${number(rows.length)} records parsed from ${e(file.name)}.</p>${field('Dataset name','name',bom?'Engineering bill of materials':file.name.replace(/\.[^.]+$/,''),'text','required')}${table(rows.slice(0,5),Object.keys(rows[0]||{}))}`,{submit:'Import dataset',wide:true,onSubmit:f=>{let id=bom?'ds-bom':uid('ds');this.store.transact(bom?'Import BOM':'Import dataset',s=>{const d={id,name:f.get('name'),source:file.name,description:'Imported local data',updated:now(),rows};const i=s.datasets.findIndex(x=>x.id===id);if(i>=0)s.datasets[i]=d;else s.datasets.push(d);});this.ui.dataset=id;this.ui.queryResults=null;this.ui.queryText='';this.ui.dataPage=0;this.render();this.toast(`${number(rows.length)} records imported`);}});}
 async runQuery(){const query=document.querySelector('#sql-query').value;const t=performance.now();this.ui.queryText=query;try{const rows=await this.worker.call('executeQuery',query,Object.fromEntries(this.state.datasets.map(d=>[d.id,d.rows])));this.ui.queryResults=rows;this.ui.dataPage=0;this.store.transact('Execute data query',s=>s.runs.push({id:uid('run'),name:'Data query',kind:'SQL subset',time:now(),status:'success',summary:`${rows.length} rows returned`,duration:performance.now()-t}),{edit:false,history:false});this.render();this.toast(`Query returned ${number(rows.length)} records`);}catch(err){this.recordFailure('Data query','SQL subset',err,performance.now()-t);throw err;}}
 async profileData(){const rows=this.ui.queryResults||this.dataset.rows,result=await this.worker.call('profile',rows);this.showModal('Dataset profile',`<p>${number(rows.length)} records · ${result.length} columns. Min/max include all finite numeric values in each column.</p>${table(result,[{key:'name',label:'Column'},{key:'type',label:'Type'},{key:'nulls',label:'Nulls'},{key:'distinct',label:'Distinct'},{key:'completeness',label:'Complete',render:v=>Math.round(v*100)+'%'},{key:'min',label:'Min'},{key:'max',label:'Max'},{key:'mean',label:'Mean',render:v=>v==null?'—':number(v,3)}])}`,{submit:null,wide:true});}
 editCell(index,key){const row=this.dataset.rows[index];if(!row)return;const original=row[key];this.showModal('Edit dataset value',`<p>Row ${index+1} · <code>${e(key)}</code></p>${field('Value','value',typeof original==='object'&&original!==null?JSON.stringify(original):original??'')}${selectField('Value type','type',['string','number','boolean','null','json'],original===null?'null':typeof original==='object'?'json':typeof original)}`,{onSubmit:f=>{let value=f.get('value');const type=f.get('type');if(type==='number'){value=Number(value);assert(Number.isFinite(value),'Enter a finite number');}else if(type==='boolean'){assert(['true','false'].includes(value),'Enter true or false');value=value==='true';}else if(type==='null')value=null;else if(type==='json')value=JSON.parse(value);this.store.transact('Edit dataset cell',()=>{this.dataset.rows[index][key]=value;this.dataset.updated=now();});this.render();}});}
 rowModal(){const row=Object.fromEntries(Object.keys(this.dataset.rows[0]||{tag:'',name:''}).map(k=>[k,null]));this.showModal('Add dataset row',`<p>Enter one JSON record using the dataset’s column names.</p><textarea class="json-editor" name="row">${e(JSON.stringify(row,null,2))}</textarea>`,{onSubmit:f=>{const value=JSON.parse(f.get('row'));assert(value&&typeof value==='object'&&!Array.isArray(value),'Expected a record object');this.store.transact('Add dataset row',()=>this.dataset.rows.push(value));this.ui.queryResults=null;this.render();}});}
 documentModal(id){const doc=this.state.documents.find(d=>d.id===id);this.showModal(doc?'Engineering document':'Add engineering document',`${field('Title','title',doc?.title||'New engineering note','text','required')}<label class="form-field"><span>Document text · indexed for lexical retrieval</span><textarea name="text" rows="12" required>${e(doc?.text||'')}</textarea></label>${field('Tags (comma separated)','tags',doc?.tags.join(', ')||'')}`,{wide:true,onSubmit:f=>{this.store.transact(doc?'Edit engineering document':'Add engineering document',s=>{const data={id:doc?.id||uid('doc'),title:f.get('title'),text:f.get('text'),tags:f.get('tags').split(',').map(s=>s.trim()).filter(Boolean)};if(doc)Object.assign(doc,data);else s.documents.push(data);});this.render();}});}
 objectModal(id){const obj=this.state.objects.find(o=>o.id===id);const value=obj||{id:uid('asset'),tag:'ASSET-'+(this.state.objects.length+1),name:'New asset',type:this.state.objectTypes[0]?.name||'Equipment',unit:'Unit 100',status:'Needs review',criticality:'Medium'};this.showModal(obj?'Edit ontology object':'Create ontology object',`<p>Edit object properties as JSON. Object IDs are stable and cannot be changed.</p><textarea name="object" class="json-editor" spellcheck="false">${e(JSON.stringify(value,null,2))}</textarea>`,{wide:true,onSubmit:f=>{const data=JSON.parse(f.get('object'));assert(data&&typeof data==='object'&&!Array.isArray(data),'Expected object');assert(data.id===value.id,'Object ID cannot change');assert(typeof data.name==='string'&&data.name.trim(),'Name is required');assert(this.state.objectTypes.some(t=>t.name===data.type),'Object type must exist in the schema');assert(!this.state.objects.some(o=>o.id!==id&&o.tag&&normTag(o.tag)===normTag(data.tag)),'An object with this tag already exists');this.store.transact(obj?'Edit ontology object':'Create ontology object',s=>{if(obj)s.objects[s.objects.findIndex(o=>o.id===id)]=data;else s.objects.push(data);});this.ui.objectSelected=data.id;this.render();}});}
 typeModal(name){const type=this.state.objectTypes.find(t=>t.name===name);this.showModal(type?'Edit object type':'Create object type',`${field('Type name','name',type?.name||'New type','text',`required ${type?'readonly':''}`)}${field('Property names (comma separated)','properties',type?.properties.join(', ')||'tag, name, status, owner','text','required')}`,{onSubmit:f=>{const n=f.get('name').trim();assert(type||!this.state.objectTypes.some(t=>t.name===n),'Type already exists');const properties=f.get('properties').split(',').map(p=>p.trim()).filter(Boolean);assert(properties.every(p=>/^[\w]+$/.test(p)&&!['__proto__','constructor','prototype'].includes(p)),'Invalid property name');this.store.transact(type?'Edit ontology type':'Create ontology type',s=>{if(type)type.properties=[...new Set(properties)];else s.objectTypes.push({name:n,properties:[...new Set(properties)]});});this.render();}});}
 linkModal(){this.showModal('Create ontology relationship',`${selectField('Source object','from',this.state.objects.map(o=>[o.id,`${o.tag} — ${o.name}`]),this.ui.objectSelected)}${field('Relationship type','type','flows to','text','required')}${selectField('Target object','to',this.state.objects.map(o=>[o.id,`${o.tag} — ${o.name}`]),this.state.objects[1]?.id)}`,{onSubmit:f=>{assert(f.get('from')!==f.get('to'),'Choose different endpoints');this.store.transact('Create ontology relationship',s=>s.links.push({id:uid('link'),...Object.fromEntries(f)}));this.render();}});}
 newPipeline(){this.showModal('Create data pipeline',`${field('Pipeline name','name','New data pipeline','text','required')}${selectField('Source dataset','dataset',this.state.datasets.map(d=>[d.id,d.name]),this.dataset?.id)}`,{submit:'Create pipeline',onSubmit:f=>{const source=uid('step'),id=uid('pipeline');this.store.transact('Create data pipeline',s=>s.pipelines.push({id,name:f.get('name'),description:'Local data pipeline',nodes:[{id:source,type:'source',name:'Source dataset',config:{dataset:f.get('dataset')},inputs:[],x:60,y:130},{id:uid('step'),type:'output',name:'Output',config:{name:f.get('name')+' output'},inputs:[source],x:340,y:130}],runs:[]}));this.ui.pipeline=id;this.ui.pipelineNode=source;this.ui.pipelineResult=null;this.render();}});}
 addBlockModal(){this.showModal('Add transformation block',`${selectField('Operation','type',['source','filter','derive','select','sort','aggregate','join','deduplicate','output'],'filter')}${field('Block name','name','New transformation','text','required')}${selectField('Input block','input',this.pipeline.nodes.map(n=>[n.id,n.name]),this.ui.pipelineNode||this.pipeline.nodes.at(-1)?.id)}`,{submit:'Add block',onSubmit:f=>{const type=f.get('type'),id=uid('step'),defaults={source:{dataset:this.state.datasets[0]?.id},filter:{expression:'true'},derive:{column:'new_value',expression:'0'},select:{columns:'tag,name'},sort:{column:'tag',desc:false},aggregate:{group:'type',op:'count',column:'*',as:'count'},join:{leftKey:'tag',rightKey:'tag',how:'left'},deduplicate:{column:'tag'},output:{name:'New output'}};this.store.transact('Add pipeline block',()=>this.pipeline.nodes.push({id,type,name:f.get('name'),config:defaults[type],inputs:type==='source'?[]:[f.get('input')],x:60+(this.pipeline.nodes.length%4)*280,y:130+Math.floor(this.pipeline.nodes.length/4)*160}));this.ui.pipelineNode=id;this.ui.pipelineResult=null;this.render();}});}
 async executePipeline(){const p=this.pipeline,t=performance.now();this.toast('Executing pipeline…');try{const result=await this.worker.call('runPipeline',clone(p),clone(this.state.datasets));this.ui.pipelineResult=result;this.store.transact('Execute data pipeline',s=>{p.runs.push({...result,id:uid('pipeline-run'),time:now()});if(p.runs.length>20)p.runs.shift();s.runs.push({id:uid('run'),kind:'pipeline',name:p.name,time:now(),status:'success',duration:result.duration,summary:`${result.rows.length} output rows; ${result.trace.length} blocks`});},{edit:false,history:false});this.render();this.toast(`Pipeline completed: ${result.rows.length} rows in ${number(result.duration,2)} ms`);}catch(err){this.recordFailure(p.name,'pipeline',err,performance.now()-t);throw err;}}
 materializePipeline(){const result=this.ui.pipelineResult||this.pipeline.runs.at(-1);assert(result?.outputs?.length,'Run a pipeline with an output block first');this.store.transact('Materialize pipeline outputs',s=>{for(const out of result.outputs){const existing=s.datasets.find(d=>d.pipeline===this.pipeline.id&&d.outputNode===out.node),data={id:existing?.id||uid('ds'),name:out.name,source:'Pipeline: '+this.pipeline.name,description:'Materialized pipeline output',updated:now(),rows:clone(out.rows),pipeline:this.pipeline.id,outputNode:out.node};if(existing)Object.assign(existing,data);else s.datasets.push(data);}});this.toast(`${result.outputs.length} output datasets saved`);this.render();}
 createThread(){const id=uid('thread');this.store.transact('Create assistant conversation',s=>s.threads.push({id,title:'New conversation',created:now(),messages:[]}),{edit:false,history:false});this.ui.thread=id;return id;}
 async sendChat(question){if(!question?.trim()||this.ui.chatBusy)return;let thread=this.state.threads.find(t=>t.id===this.ui.thread);if(!thread){this.createThread();thread=this.state.threads.find(t=>t.id===this.ui.thread);}const history=clone(thread.messages),qid=thread.id;this.store.transact('Ask grounded assistant',()=>{thread.messages.push({id:uid('message'),role:'user',text:question});if(thread.messages.length===1)thread.title=question.slice(0,52);},{edit:false,history:false});this.ui.chatBusy=true;this.updateChat();const start=performance.now();try{const answer=this.ui.modelMode==='remote'?await remoteAnswer(question,this.state,this.ui.apiKey,undefined,history):localAnswer(question,this.state);this.store.transact('Assistant response',s=>{s.threads.find(t=>t.id===qid).messages.push(answer);s.runs.push({id:uid('run'),name:'Assistant query',kind:answer.mode,time:now(),status:'success',duration:performance.now()-start,summary:question.slice(0,100)});},{edit:false,history:false});}catch(err){this.store.transact('Assistant query failed',s=>s.threads.find(t=>t.id===qid).messages.push({id:uid('message'),role:'assistant',text:'The query failed: '+err.message,citations:[],traces:[],mode:'Error'}),{edit:false,history:false});this.recordFailure('Assistant query',this.ui.modelMode,err,performance.now()-start);}finally{this.ui.chatBusy=false;this.updateChat();}}
 updateChat(){if(this.ui.drawer)this.openDrawer(true);else if(this.ui.route==='agents')this.render();}
 scrollChat(){requestAnimationFrame(()=>{const el=document.querySelector('#chat-messages');if(el)el.scrollTop=el.scrollHeight;});}
 openDrawer(refresh=false){this.ui.drawer=true;document.querySelector('.agent-drawer')?.remove();const thread=this.state.threads.find(t=>t.id===this.ui.thread),drawer=document.createElement('aside');drawer.className='agent-drawer';drawer.setAttribute('aria-label','Stratum assistant');drawer.innerHTML=`<div class="chat-top"><div class="row">${icon('spark',17)}<strong>Stratum assistant</strong>${badge(this.ui.modelMode==='remote'?'External model':'Local rules','blue')}</div><div>${ib('Open Agent Studio','open-agent-studio','upRight')}${ib('Close assistant','close-drawer','x')}</div></div><div class="chat-messages" id="chat-messages">${chatMessages(thread?.messages||[])}${this.ui.chatBusy?'<div class="loading-inline"><span class="spinner"></span>Running query…</div>':''}</div>${chatCompose(this.ui.chatBusy)}`;document.body.append(drawer);this.scrollChat();if(!refresh)drawer.querySelector('textarea')?.focus();}
 closeDrawer(){this.ui.drawer=false;document.querySelector('.agent-drawer')?.remove();}
 agentModal(){const a=this.state.agents[0];this.showModal('Configure process assistant',`${field('Agent name','name',a.name,'text','required')}${field('Description','description',a.description)}<label class="form-field"><span>System instructions (external model mode only)</span><textarea name="instructions" rows="8" required>${e(a.instructions)}</textarea></label>${notice('The local assistant uses deterministic tools. System instructions influence only explicitly configured external model calls. Model responses never execute writes automatically.')}`,{wide:true,onSubmit:f=>{this.store.transact('Configure assistant',()=>Object.assign(a,Object.fromEntries(f)));this.render();}});}
 citation(kind,id){this.closeDrawer();if(kind==='component'){this.ui.selected=id;this.ui.selectedEdge=null;this.ui.pidTab='drawing';this.navigate('pid');setTimeout(()=>this.editor?.focus(id),70);}else if(kind==='dataset'){this.ui.dataset=id;this.ui.queryResults=null;this.ui.queryText='';this.navigate('data');}else if(kind==='document')this.documentModal(id);else if(kind==='diagram'){this.ui.pidTab='drawing';this.navigate('pid');}}
 evalModal(id){const test=this.state.evaluations.find(t=>t.id===id);this.showModal(test?'Edit evaluation case':'Add evaluation case',`${field('Question','question',test?.question||'Which components need review?','text','required')}${field('Expected answer contains (case-insensitive)','expected',test?.expected||'PT-102','text','required')}`,{onSubmit:f=>{this.store.transact(test?'Edit evaluation case':'Add evaluation case',s=>{const value={id:test?.id||uid('eval'),question:f.get('question'),expected:f.get('expected')};if(test)Object.assign(test,value);else s.evaluations.push(value);});this.render();}});}
 async evaluations(){const result=await runEvaluations(this.state);this.store.transact('Run assistant evaluations',s=>{s.evaluationRuns.push(result);s.runs.push({id:uid('run'),name:'Assistant evaluation suite',kind:'evaluation',time:result.time,status:result.passed===result.total?'success':'failed',duration:result.results.reduce((n,r)=>n+r.duration,0),summary:`${result.passed}/${result.total} assertions passed`});},{edit:false,history:false});this.render();this.toast(`Evaluation complete: ${result.passed}/${result.total} assertions passed`);}
 widgetModal(id){const w=this.state.dashboard.find(w=>w.id===id);this.showModal(w?'Edit dashboard widget':'Add dashboard widget',`${field('Widget title','title',w?.title||'New metric','text','required')}${selectField('Widget type','type',[['metric','Count metric'],['chart','Numeric line chart']],w?.type||'metric')}${selectField('Data source','source',[['objects','Ontology object count'],['components','Diagram component count'],['findings','Diagram findings count'],['records','All dataset records'],...this.state.datasets.map(d=>[d.id,'Dataset: '+d.name])],w?.source||'objects')}${field('Numeric column (charts only)','column',w?.column||'pressure')}`,{onSubmit:f=>{const value={id:w?.id||uid('widget'),...Object.fromEntries(f)};assert(value.type==='metric'?['objects','components','findings','records'].includes(value.source):this.state.datasets.some(d=>d.id===value.source),'Choose a count source for a metric, or a dataset for a chart');this.store.transact(w?'Edit dashboard widget':'Add dashboard widget',s=>{if(w)Object.assign(w,value);else s.dashboard.push(value);});this.render();}});}
 automationModal(id){const a=this.state.automations.find(a=>a.id===id);this.showModal(a?'Edit automation':'Create local automation',`${field('Automation name','name',a?.name||'Validate diagram changes','text','required')}${selectField('Trigger','trigger',[['manual','Manual only'],['diagram.change','On drawing changes (while app is open)']],a?.trigger||'manual')}${selectField('Action','action',[['validate','Run structural checks'],['reconcile','Reconcile BOM']],a?.action||'validate')}<label class="checkbox-label"><input type="checkbox" name="enabled" ${a?.enabled?'checked':''}>Enable local event trigger</label>`,{onSubmit:f=>{this.store.transact(a?'Edit automation':'Create automation',s=>{const value={id:a?.id||uid('automation'),name:f.get('name'),trigger:f.get('trigger'),action:f.get('action'),enabled:f.has('enabled'),lastRun:a?.lastRun||null};if(a)Object.assign(a,value);else s.automations.push(value);});this.render();}});}
 runAutomation(id,show=true){const a=this.state.automations.find(a=>a.id===id);assert(a,'Automation not found');const t=performance.now(),result=a.action==='reconcile'?reconcileBOM(this.diagram,this.state.datasets.find(d=>d.id==='ds-bom')?.rows||[]):validateDiagram(this.diagram),summary=a.action==='reconcile'?`${result.filter(r=>r.status!=='matched').length} discrepancies`:`${result.length} structural findings`;this.store.transact('Run automation',s=>{a.lastRun=now();s.runs.push({id:uid('run'),name:a.name,kind:'automation',time:a.lastRun,status:'success',duration:performance.now()-t,summary});},{edit:false,history:false});if(show){this.render();this.toast(`${a.name}: ${summary}`);}}
 async analyzeTelemetry(){const dataset=this.state.datasets.find(d=>d.id==='ds-telemetry');assert(dataset,'No process historian dataset. Import numeric observations first.');const rows=dataset.rows.filter(r=>Number.isFinite(Number(r.pressure))),result=await gpu.anomalies(rows.map(r=>Number(r.pressure)),2.5),outliers=rows.filter((r,i)=>result.flags[i]).map((r,i)=>({...r}));this.store.transact('Analyze process telemetry',s=>s.runs.push({id:uid('run'),name:'Pressure z-score analysis',kind:result.mode,time:now(),status:'success',duration:result.duration,summary:`${outliers.length}/${rows.length} readings exceed |z| > 2.5`}),{edit:false,history:false});this.showModal('Process telemetry analysis',`<div class="summary-grid" style="grid-template-columns:repeat(3,1fr)"><div>${badge(result.mode,'green')}<h2 style="margin:10px 0">${number(result.duration,2)} ms</h2><p>Measured elapsed time</p></div><div><h2>${number(result.mean,3)} bar</h2><p>Sample mean</p></div><div><h2>${outliers.length} / ${rows.length}</h2><p>Readings beyond |z| &gt; 2.5</p></div></div>${chart(rows.map(r=>Number(r.pressure)))}${table(outliers.slice(0,30),['timestamp','tag','pressure','temperature'],{empty:'No readings exceed the chosen statistical threshold.'})}<div class="mt">${notice('z = |x − mean| / population standard deviation. This univariate rule is not a predictive-maintenance model. Data is synthetic and no control decision should be based on it.','warning')}</div>`,{wide:true,submit:null});}
 async engineDiagnostics(){const n=100000,values=Array.from({length:n},(_,i)=>Math.sin(i*.03)+(i%997===0?7:0));const result=await gpu.anomalies(values,3),expected=values.map(v=>Math.abs(v-result.mean)/(result.std||1)),error=Math.max(...result.scores.slice(0,20000).map((s,i)=>Math.abs(s-expected[i])));this.showModal('Rendering & compute diagnostics',`${table([{metric:'Engine',value:gpu.mode},{metric:'Compute path',value:result.mode},{metric:'Samples processed',value:number(n)},{metric:'Elapsed including setup and readback',value:number(result.duration,2)+' ms'},{metric:'Max absolute error on first 20,000 scores',value:error.toExponential(4)},{metric:'Scores over threshold',value:result.flags.filter(Boolean).length}],['metric','value'])}<div class="mt">${notice('This measures the current browser session, not target hardware performance. Small inputs can be faster on the CPU because GPU setup and readback have a cost.')}</div>`,{submit:null});}
 async testModel(){assert(this.state.settings.endpoint&&this.state.settings.model,'Save an endpoint and model identifier first');assert(this.state.settings.shareContext,'Enable explicit endpoint consent before making a model call');const r=await callModel({endpoint:this.state.settings.endpoint,model:this.state.settings.model,key:this.ui.apiKey,messages:[{role:'user',content:'Reply with the word connected. This is a connection test; no engineering context is supplied.'}],temperature:0});this.showModal('Model connection response',`<p>No workspace context was sent in this test.</p><div class="message-body">${e(r.text)}</div>`,{submit:null});}
 async visionDialog(){assert(this.diagram.background,'Import a raster image or PDF page before running vision extraction');assert(this.state.settings.endpoint&&this.state.settings.shareContext,'Configure an external image-capable model and explicit context-sharing consent in Models & settings');const source=clone(this.diagram);this.showModal('Send drawing to configured vision model?',`<p>The image <strong>${e(source.background.name)}</strong> will be sent to <strong>${e(new URL(this.state.settings.endpoint).host)}</strong>. The provider may charge for this request.</p>${notice('Model extraction is unverified. No detections are applied until you inspect the returned model. Existing diagram annotations will not be overwritten.','warning')}`,{submit:'Analyze image',onSubmit:async()=>{const result=await analyzeImage(source.background.data,this.state,this.ui.apiKey,source.width,source.height);setTimeout(()=>this.visionReview(result,source.id),0);}});}
 visionReview(result,diagramId){this.showModal('Review vision extraction',`<p>${result.nodes.length} components and ${result.edges.length} connections returned. Every component will be marked as requiring review.</p>${table(result.nodes.slice(0,100),['tag','name','type','x','y'])}${notice('Model-reported certainty is not treated as calibrated confidence. Reposition detections and verify all connectivity against the image.','warning')}`,{wide:true,submit:'Add unverified annotations',onSubmit:()=>{const target=this.state.diagrams.find(d=>d.id===diagramId);assert(target,'Source drawing no longer exists');const idMap=new Map(result.nodes.map(n=>[n.id,uid('node')]));this.store.transact('Add vision component candidates',()=>{target.nodes.push(...result.nodes.map(n=>({...n,id:idMap.get(n.id)})));target.edges.push(...result.edges.map(edge=>({...edge,id:uid('edge'),from:idMap.get(edge.from),to:idMap.get(edge.to)})));});this.render();this.toast('Unverified vision annotations added');}});}
 recordFailure(name,kind,error,duration){this.store.transact('Record execution failure',s=>s.runs.push({id:uid('run'),name,kind,time:now(),status:'failed',duration,summary:error.message}),{edit:false,history:false});}
 searchModal(){this.modal.className='';this.modal.innerHTML=`<input class="command-search" id="command-input" placeholder="Search tools, components, objects, and datasets…" aria-label="Search workspace"><div class="command-results" id="command-results"></div>`;this.modalSubmit=null;if(!this.modal.open)this.modal.showModal();this.searchResults('');this.modal.querySelector('input').focus();}
 searchResults(query){const q=query.toLowerCase();const items=[...routes.map(([id,label,ic])=>({name:label,detail:'Workspace tool',ic,route:id})),...this.diagram.nodes.map(n=>({name:n.tag+' · '+n.name,detail:'Diagram component · '+n.type,ic:'pid',action:'focus-component',id:n.id})),...this.state.datasets.map(d=>({name:d.name,detail:d.rows.length+' dataset records',ic:'database',action:'search-dataset',id:d.id})),...this.state.documents.map(d=>({name:d.title,detail:'Engineering document',ic:'file',action:'view-document',id:d.id}))].filter(i=>(i.name+' '+i.detail).toLowerCase().includes(q)).slice(0,22);document.querySelector('#command-results').innerHTML=items.map(item=>`<button class="command-result" ${item.route?`data-route="${item.route}"`:`data-action="${item.action==='search-dataset'?'citation':item.action}" data-id="${item.id}" ${item.action==='search-dataset'?'data-kind="dataset"':''}`}>${icon(item.ic,17)}<span>${e(item.name)}<small>${e(item.detail)}</small></span></button>`).join('')||'<div class="empty">No matching workspace resources.</div>';document.querySelectorAll('.command-result').forEach(el=>el.addEventListener('click',()=>this.closeModal(),{once:true}));}
 help(){this.showModal('Stratum Intelligence · workspace guide',`<p><strong>Diagram workflow</strong><br>Import a source or edit the sample → verify components → run structural checks → reconcile the BOM → stage publication → approve in Governance.</p><p><strong>Data workflow</strong><br>Import CSV/JSON → query and profile → build and run a pipeline → save its outputs as new datasets.</p><p><strong>Assistant workflow</strong><br>Local mode performs deterministic evidence-backed queries. External model mode requires a configured endpoint, a session API key, and explicit data-sharing consent.</p><div class="help-shortcuts">${[['⌘ / Ctrl K','Search workspace'],['⌘ / Ctrl Z','Undo'],['⌘ / Ctrl ⇧ Z','Redo'],['⌘ / Ctrl S','Save locally'],['V / H','Select / pan'],['P','Connect pipe endpoints'],['F','Fit drawing'],['R','Rotate selection'],['Delete','Delete selection'],['⌘ / Ctrl D','Duplicate selection']].map(([key,label])=>`<div><span>${label}</span><kbd>${key}</kbd></div>`).join('')}</div><div class="mt">${notice('Plain HTML, CSS, JavaScript, and WGSL. No commercial affiliation. This is an independent local-first implementation, not the full enterprise service. See the bundled README and capability matrix for exact boundaries.')}</div>`,{submit:null,wide:true});}
 mountGraph(){const host=document.querySelector('#ontology-stage');if(!host)return;this.graph=new Renderer(host,{grid:true});this.graphAbort=new AbortController();const objects=this.state.objects,selected=this.ui.objectSelected;for(let i=0;i<objects.length;i++){const o=objects[i];if(!this.graphPositions.has(o.id)){const node=this.diagram.nodes.find(n=>n.id===o.diagramNode);this.graphPositions.set(o.id,node?{x:node.x,y:node.y+60}:{x:680+Math.cos(i/objects.length*Math.PI*2)*440,y:390+Math.sin(i/objects.length*Math.PI*2)*280});}}
 const build=()=>{const scene=new Scene();const colors={Equipment:'#3673ba',Instrument:'#399389',Valve:'#9b77bd','Work order':'#bb8e39'};for(const l of this.state.links){const a=this.graphPositions.get(l.from),b=this.graphPositions.get(l.to);if(a&&b)scene.line([[a.x,a.y],[b.x,b.y]],l.from===this.ui.objectSelected||l.to===this.ui.objectSelected?'#3d84cf':'#cad5e3',l.from===this.ui.objectSelected||l.to===this.ui.objectSelected?2.4:1.4,l.type.includes('measures'));}for(const o of objects){const p=this.graphPositions.get(o.id),c=colors[o.type]||'#71869d',sel=o.id===this.ui.objectSelected;scene.circle(p.x,p.y,sel?25:20,sel?'#e7f0fc':'#ffffff',c,sel?3:1.8);scene.circle(p.x,p.y,6,c,null);scene.text(p.x,p.y+39,o.tag||o.name,{size:12,weight:600,color:c});scene.text(p.x,p.y+55,o.name.length>26?o.name.slice(0,25)+'…':o.name,{size:9,color:'#8d9aab'});}this.graph.setScene(scene);};build();requestAnimationFrame(()=>{this.graph?.resize();this.graph?.fit(1360,820,24);});let drag=null;const overlay=this.graph.overlay,signal=this.graphAbort.signal;const point=ev=>{const r=host.getBoundingClientRect();return{x:ev.clientX-r.left,y:ev.clientY-r.top};};overlay.addEventListener('pointerdown',ev=>{ev.preventDefault();const p=point(ev),w=this.graph.toWorld(p.x,p.y);const o=objects.find(o=>{const n=this.graphPositions.get(o.id);return Math.hypot(w.x-n.x,w.y-n.y)<31;});overlay.setPointerCapture(ev.pointerId);if(o){this.ui.objectSelected=o.id;drag={id:o.id};const info=document.querySelector('#ontology-object-info');if(info)info.innerHTML=ontologyObjectInfo(this.state,o);build();}else drag={view:{...this.graph.view},p};},{signal});overlay.addEventListener('pointermove',ev=>{if(!drag)return;const p=point(ev);if(drag.id){this.graphPositions.set(drag.id,this.graph.toWorld(p.x,p.y));build();}else this.graph.setView({x:drag.view.x+p.x-drag.p.x,y:drag.view.y+p.y-drag.p.y});},{signal});overlay.addEventListener('pointerup',()=>drag=null,{signal});overlay.addEventListener('pointercancel',()=>drag=null,{signal});overlay.addEventListener('wheel',ev=>{ev.preventDefault();const p=point(ev),w=this.graph.toWorld(p.x,p.y),scale=Math.min(5,Math.max(.08,this.graph.view.scale*Math.exp(-ev.deltaY*.0015)));this.graph.setView({scale,x:p.x-w.x*scale,y:p.y-w.y*scale});},{signal,passive:false});}
}

try {const store=await new Store(createSeed()).open();const app=new StratumApp(store);await app.start();}
catch(error){console.error(error);document.querySelector('#app').innerHTML=`<div class="loading-screen"><h2>Workspace could not start</h2><p>${e(error.message)}</p><p>Serve this folder over localhost or HTTPS. ES modules do not run reliably from file:// URLs.</p></div>`;}
